### ISSUE TITLE
ModuleNotFoundError: No module named 'deepke.relation_extraction.document.allennlp'

### ISSUE THREAD

**Issue by lelechallc** [zjunlp/DeepKE#100]
**Describe the bug**
> A clear and concise description of what the bug is.
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    import deepke.relation_extraction.standard.models as models
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/__init__.py", line 2, in <module>
    from .relation_extraction import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/__init__.py", line 2, in <module>
    from .document import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/document/__init__.py", line 1, in <module>
    from .model import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/document/model.py", line 6, in <module>
    from .allennlp.modules.matrix_attention import DotProductMatrixAttention, CosineMatrixAttention, BilinearMatrixAttention
ModuleNotFoundError: No module named 'deepke.relation_extraction.document.allennlp'

请问一下，这个allennlp在哪里，import失败

**Comment by tlk1997** [comment]
如果是通过pip install deepke方式导入，更新deepke包到最新版本

**Comment by lelechallc** [comment]
> 如果是通过pip install deepke方式导入，更新deepke包到最新版本

更新的时候遇到这样的错误：
Collecting seqeval==1.2.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz (43 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/luocheng_lin/anaconda3/envs/deepke/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ib0cgg2s/seqeval_fd411a6b8d174f96bd68b6c5f3767044/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ib0cgg2s/seqeval_fd411a6b8d174f96bd68b6c5f3767044/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-55yokj1x
         cwd: /tmp/pip-install-ib0cgg2s/seqeval_fd411a6b8d174f96bd68b6c5f3767044/
    Complete output (33 lines):
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
    ERROR: No matching distribution found for setuptools_scm
    Traceback (most recent call last):
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/luocheng_lin/anaconda3/envs/deepke/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpurhexbpa', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ib0cgg2s/seqeval_fd411a6b8d174f96bd68b6c5f3767044/setup.py", line 27, in <module>
        setup(
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/luocheng_lin/anaconda3/envs/deepke/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpurhexbpa', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz#sha256=f28e97c3ab96d6fcd32b648f6438ff2e09cfba87f05939da9b3970713ec56e6f (from https://pypi.tuna.tsinghua.edu.cn/simple/seqeval/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

并且还是找不到allennlp

**Comment by tlk1997** [comment]
WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
看一下这句话哈

**Comment by lelechallc** [comment]
> 如果是通过pip install deepke方式导入，更新deepke包到最新版本
感谢及时回复！！！
已经更新到deepke=2.0.0版本
但是又出现huggingface_hub模块找不到的情况，请问如何解决？
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    import deepke.relation_extraction.standard.models as models
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/__init__.py", line 2, in <module>
    from .relation_extraction import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/__init__.py", line 4, in <module>
    from .multimodal import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/multimodal/__init__.py", line 1, in <module>
    from .models import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/multimodal/models/__init__.py", line 2, in <module>
    from .IFA_model import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/multimodal/models/IFA_model.py", line 6, in <module>
    from .clip.modeling_clip import CLIPModel
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/multimodal/models/clip/__init__.py", line 2, in <module>
    from .feature_extraction_clip import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/multimodal/models/clip/feature_extraction_clip.py", line 23, in <module>
    from .feature_extraction_utils import BatchFeature, FeatureExtractionMixin, TensorType
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/multimodal/models/clip/feature_extraction_utils.py", line 37, in <module>
    from .file_utils import *
  File "/home/luocheng_lin/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/multimodal/models/clip/file_utils.py", line 51, in <module>
    from huggingface_hub import HfFolder, Repository, create_repo, list_repo_files, whoami
ModuleNotFoundError: No module named 'huggingface_hub'

**Comment by tlk1997** [comment]
你可先自己导入这个包，我们后续会在依赖中加上这个包

**Comment by lelechallc** [comment]
> huggingface_hub

感谢！！
