### ISSUE TITLE
问题麻烦解答（运行GCN和LM报错）

### ISSUE THREAD

**Issue by Naplues** [zjunlp/deepke#12]
运行GCN报错
`==========  Start training  ==========
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    train(epoch, device, train_dataloader, model, optimizer, criterion, config)
  File "/home/mere/deepke/deepke/trainer.py", line 16, in train
    y_pred = model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mere/deepke/deepke/model/GCN.py", line 32, in forward
    x = self.embedding(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mere/deepke/deepke/model/Embedding.py", line 13, in forward
    words, head_pos, tail_pos = x
ValueError: not enough values to unpack (expected 3, got 2)
`
![1](https://user-images.githubusercontent.com/25189625/67072582-c650bd00-f1b7-11e9-87f9-987d6c1e6724.png)

运行LM报错 
`==========  Start training  ==========
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    train(epoch, device, train_dataloader, model, optimizer, criterion, config)
  File "/home/mere/deepke/deepke/trainer.py", line 16, in train
    y_pred = model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mere/deepke/deepke/model/LM.py", line 19, in forward
    out = self.fc(out)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [64 x 1024], m2: [768 x 10] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:197
`
![2](https://user-images.githubusercontent.com/25189625/67072635-e97b6c80-f1b7-11e9-8ef0-da3cbd439339.png)

**Comment by yuwl798180** [comment]
你好，代码下面有报错原因提示。

1. gcn部分：
ValueError: not enough values to unpack (expected 3, got 2)
在解构输入的x值时，参数量不够。只有2个值可供解构，现在被三个值解构了。
原因是因为用gcn时需要图的邻接矩阵，进一步是用句子的parsing tree 生成的，目前中文做parsing tree 的工具还没有找到合适的，stanford nlp只能做繁体字的parsing tree。
这个稍后会暂时修改成生成虚拟的parsing tree，找到合适的工具后再替换。

2.lm部分原因：
RuntimeError: size mismatch, m1: [64 x 1024], m2: [768 x 10] 
大概率原因是你没有下载 language model的预训练模型代码，或者下载后配置部分出错了。
比如bert，默认输入的句长是512，hidden size是768，所以你可能是把hidden size改成了1024了。
这个是不能修改的，因为预训练时用的就是768。若想修改dim值，可以再后面再接全连接层进行维度长度变换。
