### ISSUE TITLE
get_labels() missing 1 required positional argument: 'cfg'

### ISSUE THREAD

**Issue by nvchungdl** [zjunlp/DeepKE#123]
**Describe the question**
> A clear and concise description of what the question is.
I have this error white try to run.py 

> (deepke) root@Ubuntu-1804-bionic-64-minimal ~/DeepKE/example/ner/standard # python run.py
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
07/08/2022 10:20:11 - INFO - deepke.relation_extraction.multimodal.models.clip.file_utils -   PyTorch version 1.10.0 available.
07/08/2022 10:20:11 - INFO - deepke.name_entity_re.multimodal.models.clip.file_utils -   PyTorch version 1.10.0 available.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive hydra/output/custom.yaml in file:///root/DeepKE/example/ner/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive train.yaml in file:///root/DeepKE/example/ner/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive predict.yaml in file:///root/DeepKE/example/ner/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Traceback (most recent call last):
  File "run.py", line 240, in <module>
    main()
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra_core-1.0.6-py3.8.egg/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "run.py", line 89, in main
    label_list = processor.get_labels()
TypeError: get_labels() missing 1 required positional argument: 'cfg'

wandb: Waiting for W&B process to finish, PID 19804... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /root/DeepKE/example/ner/standard/wandb/offline-run-20220708_102013-2k5ugm9x
wandb: Find logs at: ./wandb/offline-run-20220708_102013-2k5ugm9x/logs/debug.log

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]
conda deepke environment

**Comment by xxupiano** [comment]
Update the code https://github.com/zjunlp/DeepKE/blob/main/example/ner/standard/run.py.
