### ISSUE TITLE
bug：Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by ping40** [zjunlp/DeepKE#128]
运行：在 目录example/ner/few-shot 下，运行：python predict.py.  (   对应run.py 已经运行通过）

出现错误：
```
Traceback (most recent call last):
  File "predict.py", line 97, in main
    trainer.predict()
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 147, in predict
    preds = self._step((src_tokens, src_seq_len, first), mode="test")
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 172, in _step
    pred = self.model.predict(src_tokens, src_seq_len, first)
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 382, in predict
    prompt_state = self.prompt_model.generator(src_tokens, src_seq_len, first)    # encoder output
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 227, in generator
    past_key_values = self.get_prompt(batch_size) if self.use_prompt else None
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 239, in get_prompt
    encoder_embed = self.encoder_prompt_embed(input_tokens)
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/torch/nn/functional.py", line 2183, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

修改/home/xpeng/anaconda3/envs/kg/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py 147行代码。
原来：
```
batch = (tup.to(self.device)  if isinstance(tup, torch.Tensor) else tup for tup in batch)  # to cpu/cuda device
```
修改为：

```
batch = (tup.to(torch.device("cpu"))  if isinstance(tup, torch.Tensor) else tup for tup in batch)  # to cpu/cuda device 或者
batch = (tup.to(torch.device("cuda"))  if isinstance(tup, torch.Tensor) else tup for tup in batch)  # to cpu/cuda device

```
同样的错误。

# 运行环境：
deepke                    2.0.5                    pypi_0    pypi
python 3.8.0 版本

**Comment by Flow3rDown** [comment]
您好，预测的时候需要在`config.yaml`中添加 `- predict`，并修改`predict.yaml`中的相关参数配置，确保`device`与训练时保存模型使用的device一致。
