### ISSUE TITLE
protobuf 版本不可高于3.20.1，否则会运行错误

### ISSUE THREAD

**Issue by sunweishou** [zjunlp/DeepKE#133]
**Describe the bug**
> A clear and concise description of what the bug is.

运行示例中的命名实体识别ner预测示例程序时，protobuf版本必须回退至3.20.1版本（默认安装版本比较高，源码中未配置其版本依赖），否则会报如下两个错误：
Traceback (most recent call last):
  File "predict.py", line 1, in <module>
    from deepke.name_entity_re.standard import *
  File "D:\NLP\vdeepke\lib\site-packages\deepke\__init__.py", line 1, in <module>
    from .attribution_extraction import *
  File "D:\NLP\vdeepke\lib\site-packages\deepke\attribution_extraction\__init__.py", line 1, in <module>
    from .standard import *
  File "D:\NLP\vdeepke\lib\site-packages\deepke\attribution_extraction\standard\__init__.py", line 1, in <module>
    from .models import *
  File "D:\NLP\vdeepke\lib\site-packages\deepke\attribution_extraction\standard\models\__init__.py", line 7, in <module>
    from .LM import LM
  File "D:\NLP\vdeepke\lib\site-packages\deepke\attribution_extraction\standard\models\LM.py", line 7, in <module>
    from transformers import BertModel
  File "D:\NLP\vdeepke\lib\site-packages\transformers\__init__.py", line 22, in <module>
    from .integrations import (  # isort:skip
  File "D:\NLP\vdeepke\lib\site-packages\transformers\integrations.py", line 19, in <module>
    import wandb
  File "D:\NLP\vdeepke\lib\site-packages\wandb\__init__.py", line 32, in <module>
    from wandb import sdk as wandb_sdk
  File "D:\NLP\vdeepke\lib\site-packages\wandb\sdk\__init__.py", line 12, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "D:\NLP\vdeepke\lib\site-packages\wandb\sdk\wandb_init.py", line 35, in <module>
    from .backend.backend import Backend
  File "D:\NLP\vdeepke\lib\site-packages\wandb\sdk\backend\backend.py", line 20, in <module>
    from ..interface.interface import InterfaceBase
  File "D:\NLP\vdeepke\lib\site-packages\wandb\sdk\interface\interface.py", line 18, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "D:\NLP\vdeepke\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 15, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "D:\NLP\vdeepke\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "D:\NLP\vdeepke\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

或者：

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "D:\NLP\DeepKE\DeepKE-main-6808f15/example/ner/standard/predict_test.py", line 1, in <module>
    from deepke.name_entity_re.standard import *
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\deepke-2.0.5-py3.8.egg\deepke\__init__.py", line 1, in <module>
    from .attribution_extraction import *
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\deepke-2.0.5-py3.8.egg\deepke\attribution_extraction\__init__.py", line 1, in <module>
    from .standard import *
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\deepke-2.0.5-py3.8.egg\deepke\attribution_extraction\standard\__init__.py", line 1, in <module>
    from .models import *
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\deepke-2.0.5-py3.8.egg\deepke\attribution_extraction\standard\models\__init__.py", line
7, in <module>
    from .LM import LM
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\deepke-2.0.5-py3.8.egg\deepke\attribution_extraction\standard\models\LM.py", line 7, in
<module>
    from transformers import BertModel
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\transformers-3.4.0-py3.8.egg\transformers\__init__.py", line 135, in <module>
    from .pipelines import (
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\transformers-3.4.0-py3.8.egg\transformers\pipelines.py", line 37, in <module>
    from .tokenization_auto import AutoTokenizer
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\transformers-3.4.0-py3.8.egg\transformers\tokenization_auto.py", line 117, in <module>
    from .tokenization_albert_fast import AlbertTokenizerFast
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\transformers-3.4.0-py3.8.egg\transformers\tokenization_albert_fast.py", line 23, in <module>
    from .tokenization_utils_fast import PreTrainedTokenizerFast
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\transformers-3.4.0-py3.8.egg\transformers\tokenization_utils_fast.py", line 30, in <module>
    from .convert_slow_tokenizer import convert_slow_tokenizer
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\transformers-3.4.0-py3.8.egg\transformers\convert_slow_tokenizer.py", line 27, in <module>
    from transformers.utils import sentencepiece_model_pb2 as model
  File "d:\NLP\DeepKE\DeepKE-main-6808f15\venv\lib\site-packages\transformers-3.4.0-py3.8.egg\transformers\utils\sentencepiece_model_pb2.py", line 9, in
<module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'

**Environment (please complete the following information):**
 - OS:  Windows
 - Python Version 3.8.10

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
非常感谢您的关注，我们会尽快安排开发同学修复这一bug

**Comment by sunweishou** [comment]
> 非常感谢您的关注，我们会尽快安排开发同学修复这一bug

国内实体抽取、实体关系抽取这一块，DeepKE是个比较好的框架，其它的，除了OpenNRE，就是一些算法给的Demo了，算不上框架。DeepKE集成了非常多的模型进去，而且在中文上支持最好。希望你们团队能坚持做下去。

非常期待你们支持事件抽取的下一个版本发布@zxlzr。

**Comment by sunweishou** [comment]
> 非常感谢您的关注，我们会尽快安排开发同学修复这一bug

另外我有个调研，不知道你们是否愿意在DeepKE的实现中吸取一些目前高性能算法的实现经验？
如：
![image](https://user-images.githubusercontent.com/35616385/184827512-dc2c4bb5-1276-4103-af18-4258d97b8102.png)
等。

**Comment by zxlzr** [comment]
您的这个建议非常好，我们会先调研一下
