### ISSUE TITLE
example/ner/standard/run_bert.py异常退出

### ISSUE THREAD

**Issue by jiaolongxue** [zjunlp/DeepKE#156]
**Describe the bug**

按照文章https://zjunlp.github.io/DeepKE/example.html 使用bert训练实体识别模型时异常退出，观察内存使用率飙升到100%

Traceback (most recent call last):
  File "run_bert.py", line 142, in main
    loss = model(input_ids, segment_ids, input_mask, label_ids,valid_ids,l_mask,device)
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "run_bert.py", line 34, in forward
    sequence_output = self.bert(input_ids, token_type_ids, attention_mask,head_mask=None)[0]
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/pytorch_transformers-1.2.0-py3.8.egg/pytorch_transformers/modeling_bert.py", line 708, in forward
    encoder_outputs = self.encoder(embedding_output,
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/pytorch_transformers-1.2.0-py3.8.egg/pytorch_transformers/modeling_bert.py", line 431, in forward
    layer_outputs = layer_module(hidden_states, attention_mask, head_mask[i])
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/pytorch_transformers-1.2.0-py3.8.egg/pytorch_transformers/modeling_bert.py", line 411, in forward
    intermediate_output = self.intermediate(attention_output)
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/pytorch_transformers-1.2.0-py3.8.egg/pytorch_transformers/modeling_bert.py", line 383, in forward
    hidden_states = self.intermediate_act_fn(hidden_states)
  File "/root/miniconda3/envs/deepke/lib/python3.8/site-packages/pytorch_transformers-1.2.0-py3.8.egg/pytorch_transformers/modeling_bert.py", line 142, in gelu
    return x * 0.5 * (1.0 + torch.erf(x / math.sqrt(2.0)))
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 201326592 bytes. Error code 12 (Cannot allocate memory)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Environment (please complete the following information):**
 - OS: linux
 - cpu 8
 - mem 16GB

**Comment by xxupiano** [comment]
根据报错是因为CPU内存不足

**Comment by zxlzr** [comment]
请您kill掉多余进程重试

**Comment by jiaolongxue** [comment]
32GB以上可以运行
