### ISSUE TITLE
在re中使用lm模型报错The size of tensor a (48) must match the size of tensor b (512) at non-singleton dimension 3

### ISSUE THREAD

**Issue by sayakawaiiyo** [zjunlp/DeepKE#182]
Traceback (most recent call last):
  File "predict.py", line 141, in main
    y_pred = model(x)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/standard/models/LM.py", line 22, in forward
    a = self.bert(word, attention_mask=mask)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/transformers/modeling_bert.py", line 833, in forward
    encoder_outputs = self.encoder(
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/transformers/modeling_bert.py", line 476, in forward
    layer_outputs = layer_module(
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/transformers/modeling_bert.py", line 398, in forward
    self_attention_outputs = self.attention(
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/transformers/modeling_bert.py", line 333, in forward
    self_outputs = self.self(
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/WYF/.conda/envs/deepke/lib/python3.8/site-packages/transformers/modeling_bert.py", line 262, in forward
    attention_scores = attention_scores + attention_mask
RuntimeError: The size of tensor a (48) must match the size of tensor b (512) at non-singleton dimension 3

**Comment by tlk1997** [comment]
可以git pull下最新代码

**Comment by zxlzr** [comment]
您可以重新安装下deepke如果仍有问题麻烦贴下报错信息

**Comment by sayakawaiiyo** [comment]
重新安装后，训练模型变得非常慢，半小时只能跑1个epoch

**Comment by sayakawaiiyo** [comment]
> 您可以重新安装下deepke如果仍有问题麻烦贴下报错信息

重新安装后，训练模型变得非常慢，半小时只能跑1个epoch

**Comment by sayakawaiiyo** [comment]
> 您是否用的是cpu？使用gpu速度还是挺快的

您好，我现在跑的是ner任务中的run_bert.py文件，我发现的确是用cpu进行的训练，但我在conf中的train.yaml中use_gpu:参数设置为True,请问还需调哪里才能换成gpu'训练，谢谢

**Comment by xxupiano** [comment]
检查gpu_id是否为可用的GPU号

**Comment by sayakawaiiyo** [comment]
> 检查gpu_id是否为可用的GPU号

您好，我换成gpu训练后，报错cuda超出内存，我的显卡是1080ti 10g显存，所以我修改train_batch_size为32，但跑出结果出现问题如下
 precision    recall  f1-score   support

         LOC     0.0000    0.0000    0.0000      1799
         ORG     0.0000    0.0000    0.0000       976
         PER     0.0000    0.0000    0.0000       882

   micro avg     0.0000    0.0000    0.0000      3657
   macro avg     0.0000    0.0000    0.0000      3657
weighted avg     0.0000    0.0000    0.0000      3657

所有评价值都为0，我用跑出的checkpoints去预测也无法完成实体识别，请问这个怎么解决。谢谢

**Comment by zxlzr** [comment]
请问您是否使用的是默认下载的数据集，是否加载了预训练的模型，loss是否有下降，按照正常超参数和默认数据集是可以训出模型的，您可以检查下数据是否有问题，预训练模型是否加载和loss变化情况，以及超参数

**Comment by xxupiano** [comment]
可能使用的数据集太小，batch_size相对较大，模型没有学到什么，可以打印模型参数、loss等看看是否在训练过程中有变化
