### ISSUE TITLE
运行example/ner/few-shot/run.py报错

### ISSUE THREAD

**Issue by qinglongheu** [zjunlp/DeepKE#183]
Traceback (most recent call last):
  File "/data/qinglong/knowledgeGraph/DeepKE/example/ner/few-shot/run.py", line 101, in main
    prompt_model = PromptBartModel(tokenizer=process.tokenizer, label_ids=label_ids, args=cfg)
  File "/home/qinglong/.conda/envs/deepke/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 198, in __init__
    self.prompt_decoder = PromptBartDecoder(bart_model.decoder, tokenizer.pad_token_id, label_ids, self.use_prompt, self.prompt_len, self.learn_weights)
  File "/home/qinglong/.conda/envs/deepke/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 33, in __init__
    self.averge_weights = nn.ParameterList(parameters=None)
TypeError: __init__() got an unexpected keyword argument 'parameters'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by Flow3rDown** [comment]
您好，您的pytorch版本太高了，torch1.12版本及以后`nn.ParameterList`的参数由`parameters`变为`values`，请降低一下您的pytorch版本

**Comment by zxlzr** [comment]
您好，这个问题是pytorch版本问题，我们会在下一个大版本更新pytorch，给您带来了不便非常抱歉。
