### ISSUE TITLE
运行ner的few-shot的run.py时，ImportError: cannot import name 'AttentionUNet' from 'module'

### ISSUE THREAD

**Issue by LittleZ2022** [zjunlp/DeepKE#185]
**Describe the question**
> A clear and concise description of what the question is.

您好，在运行example\new\few-shot时报错：

Traceback (most recent call last):
  File "run.py", line 15, in <module>
    from deepke.name_entity_re.few_shot.models.model import PromptBartModel, PromptGeneratorModel
  File "F:\Anaconda3\envs\deepke\lib\site-packages\deepke\__init__.py", line 2, in <module>
    from .relation_extraction import *
  File "F:\Anaconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\__init__.py", line 2, in <module>
    from .document import *
  File "F:\Anaconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\document\__init__.py", line 1, in <module>
    from .model import *
  File "F:\Anaconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\document\model.py", line 7, in <module>
    from module import AttentionUNet, process_long_input
  File "F:\Anaconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\document\__init__.py", line 1, in <module>
    from .model import *
  File "F:\Anaconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\document\model.py", line 7, in <module>
    from module import AttentionUNet, process_long_input
ImportError: cannot import name 'AttentionUNet' from 'module' (F:\Anaconda3\envs\deepke\lib\site-packages\deepke\attribution_extraction\standard\module\
__init__.py)

**Environment (please complete the following information):**
 - OS:  window]
 - Python Version [e.g. 3.8]

**Comment by tlk1997** [comment]
可以重新安装依赖包试试，建议使用python setup.py install的方式

**Comment by LittleZ2022** [comment]
> File "F:\Anaconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\document\model.py", line 7, in from module import AttentionUNet, process_long_input 报错中这一行，对比src中https://github.com/zjunlp/DeepKE/blob/main/src/deepke/relation_extraction/document/model.py#L6 ，是不是修改过代码 找到F:\Anaconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\document\model.py文件 module前加个点

我重装一下试试
