### ISSUE TITLE
在windows上跑CNN模型出现以下错误

### ISSUE THREAD

**Issue by StCross** [zjunlp/deepke#23]
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    model_name = model.save(epoch=epoch)
  File "C:\Users\asus\Desktop\deepke\deepke\model\BasicModule.py", line 33, in save
    torch.save(self.state_dict(), name)
  File "D:\Python3.6.4\lib\site-packages\torch\serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "D:\Python3.6.4\lib\site-packages\torch\serialization.py", line 147, in _with_file_like
    f = open(f, mode)
OSError: [Errno 22] Invalid argument: 'checkpoints/CNN_epoch1_1107_19:31:57.pth'

**Comment by yuwl798180** [comment]
你好，错误原因见最后一行：os error，你好，错误原因见最后一行：os error， window 系统下目录是 右斜线，linux是左斜线，linux是左斜线
