### ISSUE TITLE
ModuleNotFoundError: No module named 'deepke.triple_extraction.PRGC.data'

### ISSUE THREAD

**Issue by Kingerdor** [zjunlp/DeepKE#250]
您好！
在执行DeepKE-main/example/re/document的时候提示import报错，貌似没有找到目录下的data.py文件，想请教一下解决的方法，谢谢！

(KingerdorDEEPKE) jovyan@gpunotebook-0:~/Kingerdor/DeepKE-main/example/re/document$ python run.py 
Traceback (most recent call last):
  File "/home/jovyan/Kingerdor/DeepKE-main/example/re/document/run.py", line 13, in <module>
    from deepke.relation_extraction.document import *
  File "/home/jovyan/Kingerdor/DeepKE-main/src/deepke/__init__.py", line 5, in <module>
    from .triple_extraction import *
  File "/home/jovyan/Kingerdor/DeepKE-main/src/deepke/triple_extraction/__init__.py", line 2, in <module>
    from .PRGC import *
  File "/home/jovyan/Kingerdor/DeepKE-main/src/deepke/triple_extraction/PRGC/__init__.py", line 1, in <module>
    from .data import *
ModuleNotFoundError: No module named 'deepke.triple_extraction.PRGC.data'

**Comment by GoooDte** [comment]
您好 只需要把/home/jovyan/Kingerdor/DeepKE-main/src/deepke/triple_extraction/PRGC/init.py文件中的from .data import *这一行删掉即可。我们已经修复了这个bug，您也可以选择重新安装。
