### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by YCA-eng** [zjunlp/DeepKE#251]
**Describe the bug**
> A clear and concise description of what the bug is.
您好！我在按照您给的readme一步一步执行，当运行到python run.py时 会出下一下错误

![1681304797873](https://user-images.githubusercontent.com/110716544/231467216-f9c21127-e206-4a1a-ac43-cec41e716279.jpg)

Traceback (most recent call last):
  File "run_bert.py", line 16, in <module>
    from deepke.name_entity_re.standard import *
  File "/public2/home/yuchunan/code/DeepKE/src/deepke/__init__.py", line 3, in <module>
    from .name_entity_re import *
  File "/public2/home/yuchunan/code/DeepKE/src/deepke/name_entity_re/__init__.py", line 4, in <module>
    from .cross import *
  File "/public2/home/yuchunan/code/DeepKE/src/deepke/name_entity_re/cross/__init__.py", line 3, in <module>
    from .seq2seq import *
  File "/public2/home/yuchunan/code/DeepKE/src/deepke/name_entity_re/cross/seq2seq/__init__.py", line 2, in <module>
    from .data_collator import *
  File "/public2/home/yuchunan/code/DeepKE/src/deepke/name_entity_re/cross/seq2seq/data_collator/__init__.py", line 5, in <module>
    from src.seq2seq.data_collator.meta_data_collator import (   # src.seq2seq.data_collator
ModuleNotFoundError: No module named 'src'

我也试图更改form这个路径 但是还会继续报这种类似的错误，请问该怎么解决
（我也是过运行其他子项目的run.py文件 ，也是出现这个错误）
**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by Flow3rDown** [comment]
安装一下`datasets`库，`pip install datasets`
