### ISSUE TITLE
NER/standard/run_bert.py异常

### ISSUE THREAD

**Issue by thunderingswolf** [zjunlp/DeepKE#252]
**Describe the bug**
**数据情况：**
valid.txt、train.txt、test.txt 只保留data.tar.gz中各第一条

**现象：**
NER/standard/run_bert.py 运行至report = classification_report(y_true, y_pred) 报错
NER/standard/run_lstmcrf.py运行正常

**错误信息：**
````
Epoch:   0% 0/3 [00:00<?, ?it/s]
Iteration:   0% 0/1 [00:00<?, ?it/s]
Iteration: 100% 1/1 [00:00<00:00,  1.20it/s]
Epoch:  33% 1/3 [00:00<00:01,  1.20it/s]
Iteration:   0% 0/1 [00:00<?, ?it/s]
Iteration: 100% 1/1 [00:00<00:00,  1.18it/s]
Epoch:  67% 2/3 [00:01<00:00,  1.18it/s]
Iteration:   0% 0/1 [00:00<?, ?it/s]
Iteration: 100% 1/1 [00:00<00:00,  1.21it/s]
Epoch: 100% 3/3 [00:02<00:00,  1.19it/s]
Evaluating: 100% 1/1 [00:00<00:00,  6.13it/s]
/home/xyzy/anaconda3/envs/DeepKE/lib/python3.8/site-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: [SEP] seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
Traceback (most recent call last):
  File "/home/xyzy/xyzy/ml/DeepKE/example/ner/standard/run_bert.py", line 250, in main
    report = classification_report(y_true, y_pred)
  File "/home/xyzy/anaconda3/envs/DeepKE/lib/python3.8/site-packages/seqeval/metrics/sequence_labeling.py", line 680, in classification_report
    target_names_pred = {type_name for type_name, _, _ in get_entities(y_pred, suffix)}
  File "/home/xyzy/anaconda3/envs/DeepKE/lib/python3.8/site-packages/seqeval/metrics/sequence_labeling.py", line 182, in get_entities
    _validate_chunk(chunk, suffix)
  File "/home/xyzy/anaconda3/envs/DeepKE/lib/python3.8/site-packages/seqeval/metrics/sequence_labeling.py", line 170, in _validate_chunk
    if not chunk.startswith(('B-', 'I-', 'E-', 'S-')):
AttributeError: 'int' object has no attribute 'startswith'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: Waiting for W&B process to finish, PID 547408... (failed 1). Press ctrl-c to abort syncing.
wandb: - 0.07MB of 0.07MB uploaded (0.00MB deduped)
wandb:                                                                                
wandb: Run history:
wandb:   train_loss █▁▇
````

**Environment (please complete the following information):**
 - OS: [ubuntu22.04]
 - Python Version [3.8.16]

**Screenshots**
![Screenshot-7](https://user-images.githubusercontent.com/18439007/231749503-0fbcf24b-e99b-4afd-87c8-14746c728123.png)

**Additional context**
**请教：**
NER/standard/run_bert.py 和 RE/standard/run.py  输出NER和RE模型，能否替换TRIPLE/cnschema中使用的模型进行预测？

**Comment by xxupiano** [comment]
训练数据太少，模型没有学习好，debug就会发现y_pred中存在[SEP]等非NER的label，建议使用few-shot NER

**Comment by thunderingswolf** [comment]
> 训练数据太少，模型没有学习好，debug就会发现y_pred中存在[SEP]等非NER的label，建议使用few-shot NER

感谢支持，我继续试一下
