### ISSUE TITLE
TypeError: typing.ClassVar[langchain.prompts.base.BasePromptTemplate] is not valid as type argument

### ISSUE THREAD

**Issue by guoliangxie123** [zjunlp/DeepKE#266]
C:\software\anaconda\1\envs\DeepKE\python.exe C:\code\python\DeepKE\example\llm\run.py 
Traceback (most recent call last):
  File "C:\code\python\DeepKE\example\llm\run.py", line 6, in <module>
    from easyinstruct.prompts import IEPrompt
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\easyinstruct\__init__.py", line 1, in <module>
    from .prompts import *
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\easyinstruct\prompts\__init__.py", line 3, in <module>
    from .index_prompt import IndexPrompt
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\easyinstruct\prompts\index_prompt.py", line 1, in <module>
    from llama_index import SimpleDirectoryReader, LLMPredictor, GPTSimpleVectorIndex
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\llama_index\__init__.py", line 14, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\llama_index\embeddings\langchain.py", line 6, in <module>
    from langchain.embeddings.base import Embeddings as LCEmbeddings
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\langchain\__init__.py", line 8, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import Agent
  File "C:\software\anaconda\1\envs\DeepKE\lib\site-packages\langchain\agents\agent.py", line 25, in <module>
    class Agent(Chain, BaseModel, ABC):
  File "pydantic\main.py", line 282, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\typing.py", line 287, in pydantic.typing.resolve_annotations
    For use of globalns and localns see the docstring for get_type_hints().
  File "C:\software\anaconda\1\envs\DeepKE\lib\typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\software\anaconda\1\envs\DeepKE\lib\typing.py", line 553, in _evaluate
    type_ = _type_check(
  File "C:\software\anaconda\1\envs\DeepKE\lib\typing.py", line 158, in _type_check
    raise TypeError(f"{arg} is not valid as type argument")
TypeError: typing.ClassVar[langchain.prompts.base.BasePromptTemplate] is not valid as type argument
---------------------------------------------------------------------------------------------------------------------------
直接运行run.py,遇到上述的报错，可以看看吗

**Comment by GoooDte** [comment]
您好 这个bug看起来是langchain包的问题，与这里的任务无关，您可以将run.py line 6的from easyinstruct.prompts import IEPrompt改为from easyinstruct.prompts.ie_prompt import IEPrompt
