### ISSUE TITLE
DeepKE/example/ee/standard gives an Error.

### ISSUE THREAD

**Issue by ping40** [zjunlp/DeepKE#291]
根据步骤，pip install -r requirements.txt 出错。

conda 环境是新环境，不存在别的包污染问题。

错误信息：
```
 pip install  -r requirements.txt
Collecting torch==1.10.0 (from -r requirements.txt (line 1))
  Using cached torch-1.10.0-cp38-cp38-manylinux1_x86_64.whl (881.9 MB)
Collecting transformers==4.26.0 (from -r requirements.txt (line 2))
  Using cached transformers-4.26.0-py3-none-any.whl (6.3 MB)
Collecting hydra-core==1.3.1 (from -r requirements.txt (line 3))
  Using cached hydra_core-1.3.1-py3-none-any.whl (154 kB)
Collecting tensorboardx==2.4 (from -r requirements.txt (line 4))
  Using cached tensorboardX-2.4-py2.py3-none-any.whl (124 kB)
Collecting lxml==4.9.1 (from -r requirements.txt (line 5))
  Using cached lxml-4.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
Collecting beautifulsoup4==4.9.3 (from -r requirements.txt (line 6))
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting bs4==0.0.1 (from -r requirements.txt (line 7))
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting stanza==1.2 (from -r requirements.txt (line 8))
  Using cached stanza-1.2-py3-none-any.whl (282 kB)
Collecting sentencepiece==0.1.95 (from -r requirements.txt (line 9))
  Using cached sentencepiece-0.1.95-cp38-cp38-manylinux2014_x86_64.whl (1.2 MB)
Collecting ipdb==0.13.9 (from -r requirements.txt (line 10))
  Using cached ipdb-0.13.9.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Collecting deepke (from -r requirements.txt (line 11))
  Using cached deepke-2.2.3.tar.gz (256 kB)
  Preparing metadata (setup.py) ... done
Collecting typing-extensions (from torch==1.10.0->-r requirements.txt (line 1))
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting filelock (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting huggingface-hub<1.0,>=0.11.0 (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached huggingface_hub-0.15.1-py3-none-any.whl (236 kB)
Collecting numpy>=1.17 (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting packaging>=20.0 (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pyyaml>=5.1 (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting regex!=2019.12.17 (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached regex-2023.6.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (772 kB)
Collecting requests (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached tokenizers-0.13.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
Collecting tqdm>=4.27 (from transformers==4.26.0->-r requirements.txt (line 2))
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting omegaconf<2.4,>=2.2 (from hydra-core==1.3.1->-r requirements.txt (line 3))
  Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Collecting antlr4-python3-runtime==4.9.* (from hydra-core==1.3.1->-r requirements.txt (line 3))
  Using cached antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Collecting importlib-resources (from hydra-core==1.3.1->-r requirements.txt (line 3))
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting protobuf>=3.8.0 (from tensorboardx==2.4->-r requirements.txt (line 4))
  Using cached protobuf-4.23.3-cp37-abi3-manylinux2014_x86_64.whl (304 kB)
Collecting soupsieve>1.2 (from beautifulsoup4==4.9.3->-r requirements.txt (line 6))
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Requirement already satisfied: setuptools in /anaconda3_public/envs/deepke/lib/python3.8/site-packages (from ipdb==0.13.9->-r requirements.txt (line 10)) (67.8.0)
Collecting ipython>=7.17.0 (from ipdb==0.13.9->-r requirements.txt (line 10))
  Using cached ipython-8.12.2-py3-none-any.whl (797 kB)
Collecting toml>=0.10.2 (from ipdb==0.13.9->-r requirements.txt (line 10))
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting decorator (from ipdb==0.13.9->-r requirements.txt (line 10))
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
INFO: pip is looking at multiple versions of deepke to determine which version is compatible with other requirements. This could take a while.
Collecting deepke (from -r requirements.txt (line 11))
  Using cached deepke-2.2.2.tar.gz (256 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-skjeqsh5/deepke_dc1c5aa904624b7f9c35adab64fa291a/setup.py", line 4, in <module>
          with open("requirements.txt") as requirements_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by xxupiano** [comment]
试一下pip install deepke==2.2.3

**Comment by ping40** [comment]
```
 requirements.txt
torch==1.10.0
transformers==4.26.0
hydra-core==1.0.6
tensorboardx==2.5.1
lxml==4.9.1
beautifulsoup4==4.9.3
bs4==0.0.1
stanza==1.2
sentencepiece==0.1.95
ipdb==0.13.11
deepke==2.2.3
```

 requirements.txt 修改成这个就可以了。
