### ISSUE TITLE
使用源码安装方法安装出现依赖解析错误的问题： Expected closing RIGHT_PARENTHESIS PyYAML (>=5.1.*)

### ISSUE THREAD

**Issue by Zilong01** [zjunlp/DeepKE#302]
系统：docker环境中Ubuntu18.04
通过使用：python setup.py install 安装程序，安装过程中报错

Installed /home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/tokenizers-0.9.2-py3.8-linux-x86_64.egg
Traceback (most recent call last):
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    PyYAML (>=5.1.*)
           ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    setup(
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
    super().run_command(command)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/command/install.py", line 137, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 416, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 750, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 832, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2821, in requires
    dm = self._dep_map
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3110, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3120, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3173, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/home/docker/anaconda3/envs/deepke/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    PyYAML (>=5.1.*)
           ~~~~~~^
           

问题分析：
1. 看起来像是在解析依赖包的情况下出现了无法解析的情况（Expected closing RIGHT_PARENTHESIS PyYAML (>=5.1.*)）
2. 我检查了`setup.py`文件中的install_requires字段，它通过requirements构建，在requirements中我没有发现 PyYAML有关的依赖
3. 同时我也尝试手动安装pip install pyyaml==5.1，但问题仍然同上。
4. 尝试更新pip依旧没有解决

请问该如何解决此问题

**Comment by tlk1997** [comment]
你好，可以尝试一下其他版本的pyyaml，我本地环境用的是5.4.1

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by Zilong01** [comment]
> 
感谢您的解答！但此问题依旧没有解决。
我尝试安装了5.4.1版本的pyyaml，然后继续python setup.py install还是会出现此问题。 此问题看起来是解析配置的依赖包时出现的格式问题，导致无法解析出错，而与依赖包本身无关。

**Comment by Zilong01** [comment]
> 你好，可以尝试一下其他版本的pyyaml，我本地环境用的是5.4.1

**感谢您的解答！但此问题依旧没有解决。
我尝试安装了5.4.1版本的pyyaml，然后继续python setup.py install还是会出现此问题。 此问题看起来是解析配置的依赖包时出现的格式问题，导致无法解析出错，而与依赖包本身无关。**

**Comment by Zilong01** [comment]
> 请问您的问题解决了吗

还没有解决

**Comment by tlk1997** [comment]
> > 你好，可以尝试一下其他版本的pyyaml，我本地环境用的是5.4.1
> 
> **感谢您的解答！但此问题依旧没有解决。 我尝试安装了5.4.1版本的pyyaml，然后继续python setup.py install还是会出现此问题。 此问题看起来是解析配置的依赖包时出现的格式问题，导致无法解析出错，而与依赖包本身无关。**

你好有其他用户也碰到了此问题，据他反馈还能继续使用本工具，该问题短期内无法得到解决，我们也将持续关注，后续若解决将第一时间进行反馈

**Comment by 2015hzz** [comment]
遇到的同样的问题

**Comment by kaihangli** [comment]
> 遇到的同样的问题

我一开始以为是pip版本或者torch版本的问题，但是实际上好像不是，我重装了好几次虚拟环境后终于解决了。
大致思路是：先创建python3.8虚拟环境→安装torch（我是3090 torch1.7.0 cu110）→直接在deepke文件夹下python setup→检查list里面deepke库是否在相对路径下

**Comment by kaihangli** [comment]
> > 请问您的问题解决了吗
> 
> 还没有解决

我一开始直接在autodl下直接源码编译成功，然后在公司的服务器上失败了，最后尝试了我上述的步骤成功安装，你可以尝试一下

**Comment by GoooDte** [comment]
大家好，为了方便大家使用，我们更新了docker的版本，新版本dockerfile位于https://github.com/zjunlp/DeepKE/tree/main/new_docker，部署方式可见https://github.com/zjunlp/DeepKE/issues/320
