### ISSUE TITLE
ner/standard/ run_bert.py 运行报错AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by maudslice** [zjunlp/DeepKE#306]
**Describe the question**
您好, 我按照文档的要求, 使用doccano进行数据标注, 使用transform_data.py转换训练数据, 并且使用lstmcrf模型完成了一轮训练, 切换到bert模型时, run_bert.py出现了错误:
```
/root/anaconda3/envs/deepke/lib/python3.9/site-packages/seqeval-1.2.2-py3.9.egg/seqeval/metrics/sequence_labeling.py:171: UserWarning: [SEP] seems not to be NE tag.
Traceback (most recent call last):
  File "/opt/deepke/DeepKE-main/example/ner/standard/run_bert.py", line 250, in main
    report = classification_report(y_true, y_pred)
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/seqeval-1.2.2-py3.9.egg/seqeval/metrics/sequence_labeling.py", line 680, in classification_report
    target_names_pred = {type_name for type_name, _, _ in get_entities(y_pred, suffix)}
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/seqeval-1.2.2-py3.9.egg/seqeval/metrics/sequence_labeling.py", line 182, in get_entities
    _validate_chunk(chunk, suffix)
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/seqeval-1.2.2-py3.9.egg/seqeval/metrics/sequence_labeling.py", line 170, in _validate_chunk
    if not chunk.startswith(('B-', 'I-', 'E-', 'S-')):
AttributeError: 'NoneType' object has no attribute 'startswith'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
conf/train.yaml 的labels字段已经进行过修改:
<img width="876" alt="截图_20230718144514" src="https://github.com/zjunlp/DeepKE/assets/52091023/222d3000-b7e7-487b-ac36-52e1c8de5ad2">

顺便想问一下, 对于特定领域的实体识别和关系抽取模型, 需要多少样本数据才能达到一个比较理想的效果

**Environment (please complete the following information):**
 - OS: centos 7.9
 - Python Version 3.9

**Comment by xxupiano** [comment]
根据报错推测是训练数据太少，如果是少样本场景，请使用ner/few-shot

**Comment by dianjinqu** [comment]
是BIO文件里面不能有空格＋O的形式，我就是这样，我把所有的空格加O都改成一个换行符就可以正常进行了。不过还没有测试空格＋B/I/E/S，我猜应该是没问题，只是O不行
