### ISSUE TITLE
你好，我在百度的数据集上运行，出现如下错误，能麻烦您帮我看一下吗

### ISSUE THREAD

**Issue by tantingting1012** [zjunlp/deepke#32]
=========  Start training  ==========
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    train(epoch, device, train_dataloader, model, optimizer, criterion, config)
  File "/home/mere/deepke/deepke/trainer.py", line 12, in train
    for batch_idx, (*x, y) in enumerate(dataloader, 1):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/mere/deepke/deepke/dataset.py", line 20, in collate_fn
    batch.sort(key=lambda data: data['seq_len'], reverse=True)
  File "/home/mere/deepke/deepke/dataset.py", line 20, in <lambda>
    batch.sort(key=lambda data: data['seq_len'], reverse=True)
KeyError: 'seq_len'

**Comment by yuwl798180** [comment]
你好，建议你学会debug下，错误信息从最后一行开始看。
上面的截图信息有用的没有截取到。

`KeyError: 'seq_len'`这里会提示你什么类型的错误，错误在哪一行，然后可以debug模式看到具体原因。

**Comment by tantingting1012** [comment]
你好，错误如下
===== start preprocess data =====
load raw files...
load data/origin/train.csv
load data/origin/test.csv
load data/origin/relation.txt

verify whether need split words...
need word segment, use jieba to split sentence
build word vocabulary...
after trim, keep words [144105 / 210128] = 68.58%
save vocab in data/out/vocab.pkl

build train data...
build test data...

save train data in data/out/train.pkl
save test data in data/out/test.pkl
===== end preprocess data =====
load data in data/out/train.pkl
load data in data/out/test.pkl
==========  Start training  ==========
<torch.utils.data.dataloader.DataLoader object at 0x7f447d91c080>
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    train(epoch, device, train_dataloader, model, optimizer, criterion, config)
  File "/home/mere/deepke/deepke/trainer.py", line 12, in train
    for batch_idx, (*x, y) in enumerate(dataloader, 1):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/mere/deepke/deepke/dataset.py", line 20, in collate_fn
    batch.sort(key=lambda data: data['seq_len'], reverse=True)
  File "/home/mere/deepke/deepke/dataset.py", line 20, in <lambda>
    batch.sort(key=lambda data: data['seq_len'], reverse=True)
KeyError: 'seq_len'

**Comment by tantingting1012** [comment]
我使用的是百度的数据，并处理成代码中ｄｅｍｏ的格式，训练出现这样的错误，这个seq_len变量在_build_data函数中返回是没有问题的

**Comment by tantingting1012** [comment]
你好，上一个问题是百度的数据带来的 ，已经解决了，目前又遇到一个问题，想请教一下您，感谢
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    train(epoch, device, train_dataloader, model, optimizer, criterion, config)
  File "/home/mere/deepke/deepke/trainer.py", line 16, in train
    y_pred = model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mere/deepke/deepke/model/LM.py", line 18, in forward
    out = self.lm(x)[0][:, 0]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 707, in forward
    embedding_output = self.embeddings(input_ids, position_ids=position_ids, token_type_ids=token_type_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 251, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 82965 out of table with 21127 rows. at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
