### ISSUE TITLE
运行 run.py报错

### ISSUE THREAD

**Issue by shnyyds** [zjunlp/DeepKE#359]
[2023-10-31 13:57:59,636][deepke.relation_extraction.standard.tools.preprocess][INFO] - clean data...
[2023-10-31 13:57:59,637][deepke.relation_extraction.standard.tools.preprocess][INFO] - convert relation into index...
[2023-10-31 13:57:59,638][deepke.relation_extraction.standard.tools.preprocess][INFO] - verify whether use pretrained language models...
[2023-10-31 13:57:59,638][deepke.relation_extraction.standard.tools.preprocess][INFO] - use pretrained language models serialize sentence...
[2023-10-31 13:57:59,638][deepke.relation_extraction.standard.tools.preprocess][INFO] - use bert tokenizer...
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f3c9eb3a0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
[2023-10-31 13:58:19,662][huggingface_hub.utils._http][WARNING] - 'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6f3c9eb3a0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
Traceback (most recent call last):
  File "run.py", line 60, in main
    preprocess(cfg)
  File "/home/shn/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke-2.2.7-py3.8.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 208, in preprocess
    _lm_serialize(train_data, cfg)
  File "/home/shn/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke-2.2.7-py3.8.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 120, in _lm_serialize
    tokenizer = BertTokenizer.from_pretrained(cfg.lm_file)
  File "/home/shn/anaconda3/envs/deepke/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/shn/anaconda3/envs/deepke/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/shn/anaconda3/envs/deepke/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/shn/anaconda3/envs/deepke/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1148, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shn/.cache/huggingface/hub/models--bert-base-chinese/refs/main'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

wandb: Waiting for W&B process to finish, PID 163607... (failed 1). Press ctrl-c to abort syncing.
wandb:                                                                                
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Synced lm: https://wandb.ai/shnhaonan/DeepKE_RE_Standard/runs/14os5c4i
wandb: Find logs at: ./logs/2023-10-31_13-57-46/wandb/run-20231031_135751-14os5c4i/logs/debug.log
wandb:

**Comment by jisong-zhu** [comment]
这个问题怎么解决的？我也遇到了同样的问题

**Comment by qssto** [comment]
这个问题怎么解决的？我也遇到了同样的问题

**Comment by yihanxiaoxiao** [comment]
这个问题怎么解决的？我也遇到了同样的问题
