### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by Nydaym** [zjunlp/DeepKE#371]
**关系抽取实验的两个疑惑点**
> 问题1：模型训练中断了，想继续训练发现好像没有这个参数，但是看fewshot方法支持中断后训练。

能否直接使用前面fewshot的方法加载已经训练过的一些权重继续训练？

> 问题2：使用其他几种非预训练模型的结构，会出现一个
```
Traceback (most recent call last):
  File "run.py", line 60, in main
    preprocess(cfg)
  File "/root/miniconda3/lib/python3.7/site-packages/deepke-2.2.7-py3.7.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 215, in preprocess
    _serialize_sentence(train_data, serial, cfg)
  File "/root/miniconda3/lib/python3.7/site-packages/deepke-2.2.7-py3.7.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 97, in _serialize_sentence
    head_idx, tail_idx = d['tokens'].index('head'), d['tokens'].index('tail')
ValueError: 'tail' is not in list
```
这个问题如何解决？我使用的是自定义的数据集

**Comment by GoooDte** [comment]
问题一：由于BERT模型不太大因此我们没有加入间断点继续训练，非常抱歉
问题二：麻烦您检查一下句子中是否包含'tail'，从报错来看应该是没有'tail'这个token

**Comment by Nydaym** [comment]
> 问题一：由于BERT模型不太大因此我们没有加入间断点继续训练，非常抱歉 问题二：麻烦您检查一下句子中是否包含'tail'，从报错来看应该是没有'tail'这个token

好的谢谢
