### ISSUE TITLE
https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt

### ISSUE THREAD

**Issue by qssto** [zjunlp/DeepKE#385]
[2023-12-25 01:35:39,333][deepke.relation_extraction.standard.tools.preprocess][INFO] - use bert tokenizer...
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f54d33d9a90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
[2023-12-25 01:35:49,355][huggingface_hub.utils._http][WARNING] - 'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f54d33d9a90>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
Traceback (most recent call last):
  File "predict.py", line 96, in main
    data, rels = _preprocess_data(data, cfg)
  File "predict.py", line 40, in _preprocess_data
    _lm_serialize(data,cfg)
  File "/root/miniconda3/lib/python3.7/site-packages/deepke-2.2.7-py3.7.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 120, in _lm_serialize
    tokenizer = BertTokenizer.from_pretrained(cfg.lm_file)
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1777, in from_pretrained
    _commit_hash=commit_hash,
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/root/miniconda3/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 1148, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--bert-base-chinese/refs/main'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

使用训练好的DeepKE(RE), RoBERTa-wwm-ext, Chinese 模型，按照要求配置了

**Comment by qssto** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/52328658/cebbd346-f5b7-4979-b9b3-f7943f94c451)

**Comment by qssto** [comment]
(base) root@f706cb09723f:~/DeepKE/example/re/standard# python predict.py 
/root/miniconda3/lib/python3.7/site-packages/hydra/core/utils.py:207: UserWarning: 
Using config_path to specify the config name is deprecated, specify the config name via config_name
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes
  warnings.warn(category=UserWarning, message=msg)
/root/miniconda3/lib/python3.7/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive hydra/output/custom.yaml in file:///root/DeepKE/example/re/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/lib/python3.7/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive preprocess.yaml in file:///root/DeepKE/example/re/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/lib/python3.7/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive train.yaml in file:///root/DeepKE/example/re/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/lib/python3.7/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive embedding.yaml in file:///root/DeepKE/example/re/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/lib/python3.7/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive predict.yaml in file:///root/DeepKE/example/re/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/lib/python3.7/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive model/lm.yaml in file:///root/DeepKE/example/re/standard/conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
/root/miniconda3/lib/python3.7/site-packages/omegaconf/basecontainer.py:232: UserWarning: cfg.pretty() is deprecated and will be removed in a future version.
Use OmegaConf.to_yaml(cfg)

  category=UserWarning,
cwd: /root/DeepKE/example/re/standard
preprocess: true
data_path: data/origin
out_path: data/out
chinese_split: true
replace_entity_with_type: true
replace_entity_with_scope: true
min_freq: 3
pos_limit: 30
seed: 1
use_gpu: true
gpu_id: 0
epoch: 50
batch_size: 32
learning_rate: 0.0003
lr_factor: 0.7
lr_patience: 3
weight_decay: 0.001
early_stopping_patience: 6
train_log: true
log_interval: 10
show_plot: false
only_comparison_plot: false
plot_utils: matplot
predict_plot: false
use_multi_gpu: false
gpu_ids: 0,1
vocab_size: ???
word_dim: 60
pos_size: 62
pos_dim: 10
dim_strategy: sum
num_relations: 51
fp: /root/DeepKE/example/re/standard/checkpoints/re_robert.pth
model_name: lm
lm_file: bert-base-chinese
num_hidden_layers: 1
type_rnn: LSTM
input_size: 768
hidden_size: 100
num_layers: 1
dropout: 0.3
bidirectional: true
last_layer_hn: true

是否使用范例[y/n]，退出请输入: exit .... y
[2023-12-25 02:29:23,033][deepke.relation_extraction.standard.tools.preprocess][INFO] - use bert tokenizer...
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcbb08ad810>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
[2023-12-25 02:29:33,052][huggingface_hub.utils._http][WARNING] - 'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcbb08ad810>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
Traceback (most recent call last):
  File "predict.py", line 96, in main
    data, rels = _preprocess_data(data, cfg)
  File "predict.py", line 40, in _preprocess_data
    _lm_serialize(data,cfg)
  File "/root/miniconda3/lib/python3.7/site-packages/deepke-2.2.7-py3.7.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 120, in _lm_serialize
    tokenizer = BertTokenizer.from_pretrained(cfg.lm_file)
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1777, in from_pretrained
    _commit_hash=commit_hash,
  File "/root/miniconda3/lib/python3.7/site-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/root/miniconda3/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 1148, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--bert-base-chinese/refs/main'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by GoooDte** [comment]
您好，建议您清空/root/.cache/中的文件重新下载模型，现在国内huggingface需要科学上网方式下载，或者参考https://hf-mirror.com/中在镜像网站下载到本地加载

**Comment by qssto** [comment]
> 您好，建议您清空/root/.cache/中的文件重新下载模型，现在国内huggingface需要科学上网方式下载，或者参考 https://hf-mirror.com/ 中在镜像网站下载到本地加载

您好，这个框架内的内容为什么还需要访问外网呀，要是我私有化部署也需要访问外网吗

**Comment by qssto** [comment]
> 您好，建议您清空/root/.cache/中的文件重新下载模型，现在国内huggingface需要科学上网方式下载，或者参考 https://hf-mirror.com/ 中在镜像网站下载到本地加载

训练模型是用：DeepKE-cnSchema  这个，重新下载还是报一样的内容

**Comment by qssto** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/52328658/cae6bcf0-5a87-4ce7-b78c-f5dac50f9e0b)
目前使用：参考 https://hf-mirror.com/ 中在镜像网站下载到本地加载 ，方法三解决，
