### ISSUE TITLE
运行结果

### ISSUE THREAD

**Issue by liyuanzhe1** [zjunlp/DeepKE#391]
**Describe the question**
> A clear and concise description of what the question is.

Traceback (most recent call last):
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 198, in run_and_report
    return func()
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\hydra.py", line 100, in run
    cfg = self.compose_config(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 224, in _load_configuration
    job_cfg, job_cfg_load_trace = self._load_primary_config(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 819, in _load_primary_config
    ret, load_trace = self._load_config_impl(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 589, in _load_config_impl
    ret = self.repository.load_config(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\config_repository.py", line 45, in load_config
    ret = source.load_config(
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\hydra\_internal\core_plugins\file_config_source.py", line 42, in load_config
    cfg = OmegaConf.load(f)
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\omegaconf\omegaconf.py", line 262, in load
    obj = yaml.load(file_, Loader=get_yaml_loader())
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\scanner.py", line 1149, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "G:\PY3\anaconda3\envs\deepke\lib\site-packages\yaml\scanner.py", line 1223, in scan_flow_scalar_non_spaces
    raise ScannerError("while scanning a double-quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "G:\DeepKE-main\example\ner\standard\conf\config.yaml", line 6, column 6
found unknown escape character 'D'
  in "G:\DeepKE-main\example\ner\standard\conf\config.yaml", line 6, column 10
这个该如何解决，运行之后出现这些warning，而且没有运行结果
![image](https://github.com/zjunlp/DeepKE/assets/150209745/f5689758-6d22-412a-bd9e-b2bccdc0edfb)

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by GoooDte** [comment]
您好，看起来是"G:\DeepKE-main\example\ner\standard\conf\config.yaml", line 6, column 6有语法错误，建议您进行检查
