### ISSUE TITLE
cnschema 用不了

### ISSUE THREAD

**Issue by Lowpower** [zjunlp/DeepKE#393]
[2024-01-06 18:44:38,799][pytorch_transformers.modeling_utils][INFO] - loading weights file ./models/checkpoints_robert/pytorch_model.bin
[2024-01-06 18:44:41,478][pytorch_transformers.tokenization_utils][INFO] - Model name './models/checkpoints_robert' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). Assuming './models/checkpoints_robert' is a path or url to a directory containing tokenizer files.

**Comment by GoooDte** [comment]
您好，您需要将模型下载到本地./models/checkpoints_robert路径下

**Comment by Lowpower** [comment]
/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/rnn.py:82: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.3 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
Traceback (most recent call last):
  File "predict.py", line 122, in <module>
    main()
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "predict.py", line 104, in main
    model.load(cfg.refp, device=device)
  File "/Users/shengzhiqiang/dev/LLM/DeepKE/example/triple/cnschema/LMModel.py", line 23, in load
    self.load_state_dict(torch.load(path, map_location=device))
  File "/Users/shengzhiqiang/miniconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LM:
        Unexpected key(s) in state_dict: "bert.embeddings.position_ids".

**Comment by Lowpower** [comment]
> 您好，您需要将模型下载到本地./models/checkpoints_robert路径下

是在这个路径，但是只有model能正常加载，BertTokenizer就会重新下载

**Comment by Lowpower** [comment]
added_tokens.json       config.json             eval_results.txt        model_config.json       pytorch_model.bin       special_tokens_map.json tokenizer_config.json   vocab.txt

**Comment by Lowpower** [comment]
并且执行到最后还有这个错误
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LM:
        Unexpected key(s) in state_dict: "bert.embeddings.position_ids".

**Comment by GoooDte** [comment]
您的模型是在这里下载的吗https://github.com/zjunlp/DeepKE/tree/main/example/triple/cnschema#chinese-model-download

**Comment by Lowpower** [comment]
是的，google download

**Comment by Lowpower** [comment]
text: '此外网易云平台还上架了一系列歌曲，其中包括田馥甄的《小幸运》等'
nerfp: './models/checkpoints_robert'
refp: './models/RE/re_robert.pth'

**Comment by GoooDte** [comment]
除了模型参数外其他文件可以使用从huggingface下载的，应该没有变化

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by Lowpower** [comment]
> 请问您的问题是否已解决？

没有

**Comment by Lowpower** [comment]
> 除了模型参数外其他文件可以使用从huggingface下载的，应该没有变化

我试一下

**Comment by Lowpower** [comment]
> 请问您的问题是否已解决？

没有

**Comment by zxlzr** [comment]
您好，我们没有复现出您的问题，建议您换台机器再试一下或者重装conda环境重试一下。
