### ISSUE TITLE
在使用LLMICL时，使用英文上下文提示没问题，但使用中文上下文提示就会报错

### ISSUE THREAD

**Issue by Euphoria0924** [zjunlp/DeepKE#395]
Error executing job with overrides: []
Traceback (most recent call last):
  File "D:\PycharmProjects\KGdemo\DeepKE-main\example\llm\LLMICL\run.py", line 47, in main
    ie_prompter.build_prompt(
  File "D:\anaconda3\envs\deepke-llm\lib\site-packages\easyinstruct\prompts\ie_prompt.py", line 123, in build_prompt
    examples = self._get_incontext_examples(examples)
  File "D:\anaconda3\envs\deepke-llm\lib\site-packages\easyinstruct\prompts\ie_prompt.py", line 269, in _get_incontext_examples
    self.examples.append({"输出": str(example["output"])})
KeyError: 'output'
小白入门，请赐教

**Comment by guihonghao** [comment]
你的示例数据example中不包含"output"字段

**Comment by Euphoria0924** [comment]
> 你的示例数据example中不包含"output"字段

你好，十分感谢及时回复！示例中不包含output但是通过了preprocess.py处理过后转换成了识别示例中的data字段，这个data字段在英文示例中存在，运行没有报错；但同样格式的中文示例虽然存在该字段，却无法识别该字段并且报错。

**Comment by guihonghao** [comment]
看看你转换后的数据。example中需要包含"output"字段。

**Comment by Euphoria0924** [comment]
你好，转换的结果如下：Error executing job with overrides: []
[{'output': [{'E': 'ORG', 'W': '国务院'}, {'E': 'PER', 'W': '秦始皇'}, {'E': 'LOC', 'W': '陕西省'}, {'E': 'LOC', 'W': '西安市'}, {'E': 'TIME', 'W': '1961年'}]}]
Traceback (most recent call last):
  File "D:\PycharmProjects\KGdemo\DeepKE-main\example\llm\LLMICL\run.py", line 47, in main
    ie_prompter.build_prompt(
  File "D:\anaconda3\envs\deepke-llm\lib\site-packages\easyinstruct\prompts\ie_prompt.py", line 123, in build_prompt
    examples = self._get_incontext_examples(examples)
  File "D:\anaconda3\envs\deepke-llm\lib\site-packages\easyinstruct\prompts\ie_prompt.py", line 272, in _get_incontext_examples
    self.examples.append({"输出": str(example["output"])})
KeyError: 'output'

**Comment by Euphoria0924** [comment]
已经解决，原因是easyinstruct包下的ie_prompt文件第263行 for example in **self**.examples ,需要将self删去，感谢大家帮助，😄
