### ISSUE TITLE
DeepKE/example/ee/standard 多网卡训练错误

### ISSUE THREAD

**Issue by ping40** [zjunlp/DeepKE#408]
单网卡没有问题， 多网卡有问题。

代码最新，环境按照requirement.txt   要求的。

deepke 是通过下面方式安装的：

```
pip install -r requirements.txt

python setup.py install

python setup.py develop
```

安装结果是：

```
conda list

deepke                    2.2.7                     dev_0    <develop>
```

按照 文档 [https://github.com/zjunlp/DeepKE/tree/main/example/ee/standard#readme，](https://github.com/zjunlp/DeepKE/tree/main/example/ee/standard#readme%EF%BC%8C)

先执行 python run.py (用 DuEE数据, task_name = trigger）
, 出现如下错误：

```
[2024-02-01 10:15:48,930][__main__][INFO] -   Num examples = 1498
[2024-02-01 10:15:48,930][__main__][INFO] -   Batch size = 32
[2024-02-01 10:15:48,930][__main__][INFO] -   Mode = dev
Evaluating:   0%|                                                                                                                                                                           | 0/47 [00:00<?, ?it/s]
Iteration:  33%|█████████████████████████████████████████████████████▊                                                                                                           | 125/374 [01:23<02:46,  1.50it/s]
Epoch:  50%|████████████████████████████████████████████████████████████████████████████████████                                                                                    | 1/2 [05:38<05:38, 338.84s/it]
Error executing job with overrides: []
Traceback (most recent call last):
  File "run.py", line 405, in main
    global_step, tr_loss = train(
  File "run.py", line 150, in train
    results, _ = evaluate(args, model, eval_dataset, tokenizer, labels, pad_token_label_id, mode="dev", device=device)
  File "run.py", line 218, in evaluate
    outputs = model(pad_token_label_id=pad_token_label_id, **inputs)
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/modelenv/anaconda3/envs/deepke-source/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 154, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by ping40** [comment]
但是我屏蔽了 evaluate方法中的DataParallel，运行是通过的

```
def evaluate(args, model, eval_dataset, tokenizer, labels, pad_token_label_id, mode, device, prefix=""):

    OmegaConf.set_struct(args, True)
    with open_dict(args):
        args.eval_batch_size = args.per_gpu_eval_batch_size * max(1, args.n_gpu)
    
    # Note that DistributedSampler samples randomly
    eval_sampler = SequentialSampler(eval_dataset) if args.local_rank == -1 else DistributedSampler(eval_dataset)
    eval_dataloader = DataLoader(eval_dataset, sampler=eval_sampler, batch_size=args.eval_batch_size)

    # multi-gpu evaluate
    if args.n_gpu > 1:
        #model = torch.nn.DataParallel(model)   -->屏蔽这行
        pass ---》 增加这行

```

多卡训练速度反而慢了， 但是f1, precision的数值提高了。 这是期望的结果吗 ？
我原来的期望是：多卡训练速度应该加快，但是f1, precision的数值应该没有影响的。

谢谢高手指导

**Comment by shengyumao** [comment]
你好，我们的代码之前实现的时候并没有考虑支持多卡上的运行以及调试。多卡的训练可能会因为不同卡之间的通讯开销导致训练速度变慢，所以在gpu容量满足的情况下单卡的训练速度一般来说会快一些。至于f1数值的变化可能是由于一些随机性的波动造成的。
