### ISSUE TITLE
求大佬救

### ISSUE THREAD

**Issue by HEjiEheJIej** [zjunlp/DeepKE#416]
**Describe the question**
> A clear and concise description of what the question is.
在虚拟环境运行deepke中ner的python run_lstmcrf.py和python run_bert.py这两个指令的时候，错误提示我要正确的配置hydra的custom.yaml的文件，但是我已经加入了@package指令但依然报错
这是我修改后的custom.yaml文件
@package hydra.output

hydra:

  run:
    # Output directory for normal runs
    dir: logs/${now:%Y-%m-%d_%H-%M-%S}

  sweep:
    # Output directory for sweep runs
    dir: logs/${now:%Y-%m-%d_%H-%M-%S}
    # Output sub directory for sweep runs.
    subdir: ${hydra.job.num}_${hydra.job.id}

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

window
3.8

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by xxupiano** [comment]
您好，请您截一张报错的截图

**Comment by HEjiEheJIej** [comment]
您好，可能是我的浏览器问题图片上传不了



---- 回复的原邮件 ----
| 发件人 | Xin ***@***.***> |
| 日期 | 2024年03月03日 14:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 求大佬救 (Issue #416) |

您好，请您截一张报错的截图

**Comment by HEjiEheJIej** [comment]
可以在邮箱里给您回吗



---- 回复的原邮件 ----
| 发件人 | Xin ***@***.***> |
| 日期 | 2024年03月03日 14:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 求大佬救 (Issue #416) |

您好，请您截一张报错的截图

**Comment by xxupiano** [comment]
可以在这个github邮件下发张图片试试？

**Comment by zxlzr** [comment]
您可以在issue里贴图片

**Comment by zxlzr** [comment]
您好，建议您在linux 环境用anaconda 虚拟环境按readme安装，windows 很多包兼容性不好

**Comment by HEjiEheJIej** [comment]
您发给我的被封锁了



---- 回复的原邮件 ----
| 发件人 | Xin ***@***.***> |
| 日期 | 2024年03月03日 15:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zjunlp/DeepKE] 求大佬救 (Issue #416) |

可以在这个github邮件下发张图片试试？

**Comment by zxlzr** [comment]
> 您发给我的被封锁了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | Xin ***@***.***> | | 日期 | 2024年03月03日 15:33 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [zjunlp/DeepKE] 求大佬救 (Issue #416) | 可以在这个github邮件下发张图片试试？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

您可以在github issue里贴报错图片

**Comment by HEjiEheJIej** [comment]
![Uploading 屏幕截图 2024-03-03 143206.jpg…]()

**Comment by HEjiEheJIej** [comment]
(deepke) E:\DeepKe\DeepKE-main\example\ner\standard>python run_lstmcrf.py
wandb: Currently logged in as: 18758509134 (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.16.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.7
wandb: Syncing run firm-field-19
wandb:  View project at https://wandb.ai/18758509134/DeepKE_NER_Standard
wandb:  View run at https://wandb.ai/18758509134/DeepKE_NER_Standard/runs/s2vcxlul
wandb: Run data is saved locally in E:\DeepKe\DeepKE-main\example\ner\standard\wandb\run-20240304_115356-s2vcxlul
wandb: Run `wandb offline` to turn off syncing.

E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\plugins\config_source.py:190: UserWarning:
Missing @package directive hydra/output/custom.yaml in file://E:\DeepKe\DeepKE-main\example\ner\standard\conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Traceback (most recent call last):
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 198, in run_and_report
    return func()
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\hydra.py", line 100, in run
    cfg = self.compose_config(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 256, in _load_configuration
    cfg = self._merge_defaults_into_config(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 804, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, system_list)
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 777, in merge_defaults_list_into_config
    merged_cfg = self._merge_config(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 695, in _merge_config
    loaded_cfg, _ = self._load_config_impl(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 589, in _load_config_impl
    ret = self.repository.load_config(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_repository.py", line 45, in load_config
    ret = source.load_config(
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\hydra\_internal\core_plugins\file_config_source.py", line 42, in load_config
    cfg = OmegaConf.load(f)
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\omegaconf\omegaconf.py", line 262, in load
    obj = yaml.load(file_, Loader=get_yaml_loader())
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\yaml\composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\yaml\parser.py", line 142, in parse_implicit_document_start
    if not self.check_token(DirectiveToken, DocumentStartToken,
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "E:\Anaconda\anaconda\envs\deepke\lib\site-packages\yaml\scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '@' that cannot start any token
  in "E:\DeepKe\DeepKE-main\example\ner\standard\conf\hydra\output\custom.yaml", line 1, column 1

wandb: Waiting for W&B process to finish, PID 3584... (failed 1). Press ctrl-c to abort syncing.
wandb: Network error (TransientError), entering retry loop.
wandb: | 0.00MB of 0.01MB uploaded (0.00MB deduped)
只能这样了

**Comment by HEjiEheJIej** [comment]
> 您好，建议您在linux 环境用anaconda 虚拟环境按readme安装，windows 很多包兼容性不好

可以直接在windows中用anaconda的虚拟环境吗

**Comment by zxlzr** [comment]
建议您直接使用linux环境，可以省去很多麻烦节省时间。因为windows环境下很多库兼容性很差，很多库高级版本都不支持windows。

理论上只要安装正确版本的库在windows下可以正常运行。

**Comment by zxlzr** [comment]
请问您的问题解决了吗
