### ISSUE TITLE
 No such file or directory: 'C:\\Users\\LiuJunshan\\Desktop\\DeepKE-main\\DeepKE-main\\example\\re\\standard\\data/out\\train.pkl'

### ISSUE THREAD

**Issue by liujunshanhelen** [zjunlp/DeepKE#418]
[2024-03-04 22:09:13,485][__main__][INFO] - device: cpu
[2024-03-04 22:09:13,486][utils.ioUtils][INFO] - load data from C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\data/out\train.pkl
Traceback (most recent call last):
  File "C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\run.py", line 74, in main
    train_dataset = CustomDataset(train_data_path)
  File "C:\Users\LiuJunshan\miniconda3\envs\deepke\lib\site-packages\deepke\relation_extraction\standard\tools\dataset.py", line 64, in __init__
    self.file = load_pkl(fp)
  File "C:\Users\LiuJunshan\miniconda3\envs\deepke\lib\site-packages\deepke\attribution_extraction\standard\utils\ioUtils.py", line 36, in load_pkl
    with open(fp, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\LiuJunshan\\Desktop\\DeepKE-main\\DeepKE-main\\example\\re\\standard\\data/out\\train.pkl'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by zxlzr** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\LiuJunshan\Desktop\DeepKE-main\DeepKE-main\example\re\standard\data/out\train.pkl'

请您自行检查一下对应路径下是否有文件夹和相应文件，如standard下的data文件夹、out文件夹

**Comment by xxupiano** [comment]
"data/out" is the path style of Linux. However, you are using Windows OS. Please rectify the path.

**Comment by zxlzr** [comment]
请问您的问题解决了吗
