### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by wangguanhua** [zjunlp/deepke#42]
您好，您项目中所给数据顺利跑通。但换成自己的数据时，疯狂报KeyError，每一个字段都曾报过，最后一个KeyError: 'index'实在是解决不了了。数据格式与您要求的一样。报错信息如下Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main()
  File "/home/wgh/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/wgh/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/wgh/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/wgh/anaconda3/envs/pytorch/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 46, in main
    preprocess(cfg)
  File "/home/wgh/deepke/preprocess.py", line 116, in preprocess
    rels = _handle_relation_data(relation_data)
  File "/home/wgh/deepke/preprocess.py", line 90, in _handle_relation_data
    relation_data = sorted(relation_data, key=lambda i: int(i['index']))
  File "/home/wgh/deepke/preprocess.py", line 90, in <lambda>
    relation_data = sorted(relation_data, key=lambda i: int(i['index']))
KeyError: 'index'

**Comment by yuwl798180** [comment]
你好，index这个key当初设想是句子中存在相同实体时防止错误标记位置。
举个例子：南京大学位于南京的东北方。那么 <南京大学，南京>这个实体中，tail的南京 index 应该是6而不是0。
之所以需要强调这点，是因为后续会对头尾实体的位置做特殊标注。
比如上面例子会处理成：<e1>南京大学</e1>位于<e2>南京</e2>的东北方。
如果头尾实体有重叠，就会导致这种处理出现错误。
同时还有另一种情况：句子有相同实体。比如：南京大学位于南京的东北方，南京大学新校区的风景很美丽。后一个南京大学和南京并不是我们所希望判断关系的实体对。
当然，如果你的语料中这些特殊情况没有，或者比较少可以忽略不计，那么index这个key确实是不需要的。
之前我把这块写死了，后续会更改掉。

**Comment by yuwl798180** [comment]
不好意思，刚看了你的报错信息，我弄错了。。

你的报错信息是（看最后一行）：
```
File "/home/wgh/deepke/preprocess.py", line 90, in
relation_data = sorted(relation_data, key=lambda i: int(i['index']))
KeyError: 'index'
```
这句话意思就是：你的 `relation.csv` 文件里没有 `index` 这一列。
我们需要把关系也序列化一下的，比如10个关系，那么就序列化为1-10（其中0为NA)。

**Comment by wangguanhua** [comment]
额，我数据集里是有index的，我所有数据集都是按照你的格式做的。不止index，head，tail等都曾爆keyerror。当我把你main.py内所说可注释掉的两行代码注释掉后，程序正常运行。

**Comment by yuwl798180** [comment]
你注释掉的两行是预处理的代码。。
注释掉了，你是怎么运行通顺的呀，难道你之前已经预处理过了？
建议你再检查下data文件，`relation.csv`是一个 `csv`，是不是格式错误的问题。

**Comment by cqguowangshu** [comment]
您好！我在学习您的deepke源代码，并试图复现相关实验，但是在使用Bert的时候（model=lm），一直报无法找到预训练模型的错误，错误代码为：Model name '/deepke-master/deepke-master/pretrained' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased). We assumed '/deepke-master/deepke-master/pretrained' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
    但是我是严格按照readme中的要求，下载了完整的bert模型（pytorch版）并放置在pretrained文件夹内，不知是何错误？
    还有一个小问题，源代码中在predict里运行后有“实体类型”输入这一选项，但给出的train data格式中并没有“实体类型”，是否意味着我可以在训练数据中自行添加“实体类型”的训练特征，而后的预测也可以因此提高精确度？
    请批评指正！望不吝赐教！谢谢！

**Comment by wangguanhua** [comment]
您好，关于keyerr这个我试了很多次，还是报错。
    main()
  File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 46, in main
    preprocess(cfg)
  File "/home/wgh/deepke/preprocess.py", line 118, in preprocess
    _add_relation_data(rels, train_data)
  File "/home/wgh/deepke/preprocess.py", line 84, in _add_relation_data
    d['rel2idx'] = rels[d['relation']]['index']
KeyError: '\u4e88\u8d85\u58f0\u836f\u7269\u900f\u5165\u6cbb\u7597\u3001\u4f4e\u9891\u8109\u51b2\u7535\u6cbb\u7597\u3001\u7a74\u4f4d\u8d34\u6577\u6cbb\u7597\uff0c\u57cb\u9488\u7535\u6cbb\u7597\u7b49\u5eb7\u590d\u7406\u7597'
csv文件我检查多次，格式和你的一摸一样。
![image](https://user-images.githubusercontent.com/25172472/89187024-3f969080-d5cf-11ea-974b-0ad12b895dbb.png)

**Comment by cqguowangshu** [comment]
经过我多次测试，还没发现根本的问题，但是我认为应该是训练数据有问题。肯定有少部分的错误数据没有符合格式要求，建议你用try except将问题数据打印出来。我在使用bert模式时候是能够跑通的，所以应该是embedding位置报的错，所有我猜是自己的训练数据有问题。
















在 2020-08-03 21:21:34，"wangguanhua" <notifications@github.com> 写道：

您好，关于keyerr这个我试了很多次，还是报错。
main()
File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
strict=strict,
File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
overrides=args.overrides,
File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
job_subdir_key=None,
File "/home/wgh/anaconda3/envs/pytor/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
ret.return_value = task_function(task_cfg)
File "main.py", line 46, in main
preprocess(cfg)
File "/home/wgh/deepke/preprocess.py", line 118, in preprocess
_add_relation_data(rels, train_data)
File "/home/wgh/deepke/preprocess.py", line 84, in _add_relation_data
d['rel2idx'] = rels[d['relation']]['index']
KeyError: '\u4e88\u8d85\u58f0\u836f\u7269\u900f\u5165\u6cbb\u7597\u3001\u4f4e\u9891\u8109\u51b2\u7535\u6cbb\u7597\u3001\u7a74\u4f4d\u8d34\u6577\u6cbb\u7597\uff0c\u57cb\u9488\u7535\u6cbb\u7597\u7b49\u5eb7\u590d\u7406\u7597'
csv文件我检查多次，格式和你的一摸一样。

**Comment by wangguanhua** [comment]
是的，我发现是训练集的问题。报错代码中有index，我还以为是包含关系的那个csv。麻烦您了



---Original---
