### ISSUE TITLE
按照教程数据集下载格式是csv，DeepKE/example/re/standard/data/out/train.pkl，这个文件是生成吗？

### ISSUE THREAD

**Issue by liujunshanhelen** [zjunlp/DeepKE#421]
![1](https://github.com/zjunlp/DeepKE/assets/99471899/965dd05f-04bb-43c8-88ab-53eb4dbdf7b8)

![2](https://github.com/zjunlp/DeepKE/assets/99471899/74691228-2c4c-435e-b228-3e27e27b9bc1)
Traceback (most recent call last):
  File "run.py", line 74, in main
    train_dataset = CustomDataset(train_data_path)
  File "/home/ljs/miniconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/standard/tools/dataset.py", line 64, in __init__
    self.file = load_pkl(fp)
  File "/home/ljs/miniconda3/envs/deepke/lib/python3.8/site-packages/deepke/attribution_extraction/standard/utils/ioUtils.py", line 36, in load_pkl
    with open(fp, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ljs/DeepKE/example/re/standard/data/out/train.pkl'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by xxupiano** [comment]
https://github.com/zjunlp/DeepKE/blob/5c9baaad70b5c5e6ca40f1a6b8c13df8ecdf45c3/example/re/standard/run.py#L60 这里的预处理会输出.pkl，请不要注释掉

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by liujunshanhelen** [comment]
解决了
