### ISSUE TITLE
re few-shot中hydra配置问题

### ISSUE THREAD

**Issue by XiChen211** [zjunlp/DeepKE#438]
**Describe the bug**
> A clear and concise description of what the bug is.
re few-shot按照示例步骤配置完环境，下载完数据集后，尝试运行run.py，出现hydra.errors.MissingConfigException: Could not load override hydra/output/custom
![image](https://github.com/zjunlp/DeepKE/assets/129187011/c99163bb-1cb2-4718-baa1-8cd609a91d14)

**Comment by zxlzr** [comment]
请您重新拉取代码跑一下试一试

**Comment by xxupiano** [comment]
请检查hydra版本

**Comment by XiChen211** [comment]
> 请您重新拉取代码跑一下试一试

![image](https://github.com/zjunlp/DeepKE/assets/129187011/e5a709fb-d3cc-4e6e-9b52-a5fdd35a8036)
您好，我重新拉取了代码还是出现同样的问题。

**Comment by XiChen211** [comment]
> 请检查hydra版本

![image](https://github.com/zjunlp/DeepKE/assets/129187011/eeea3ce2-c9ce-409f-b5e4-a8ace9dc4153)
您好，我的hydra版本是按照requirements要求的1.0.6

**Comment by flow3rdown** [comment]
配置文件有问题，您可以拉取一下最新代码或者手动把`DeepKE/example/re/few-shot/conf/config.yaml`改为：
```python
cwd: ???

defaults:
  - hydra/output: custom
  - train
```

**Comment by zxlzr** [comment]
请问您问题解决了吗

**Comment by XiChen211** [comment]
> 配置文件有问题，您可以拉取一下最新代码或者手动把`DeepKE/example/re/few-shot/conf/config.yaml`改为：
> 
> ```python
> cwd: ???
> 
> defaults:
>   - hydra/output: custom
>   - train
> ```

谢谢您，更改配置之后就可以训练模型了。

**Comment by XiChen211** [comment]
> 请问您问题解决了吗

谢谢您，问题已解决。

**Comment by meimengiii** [comment]
Traceback (most recent call last):
  File "D:/DeepKE-main/example/re/standard/run.py", line 178, in <module>
    main()
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\main.py", line 32, in decorated_main
    _run_hydra(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 346, in _run_hydra
    run_and_report(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 201, in run_and_report
    raise ex
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 198, in run_and_report
    return func()
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\hydra.py", line 100, in run
    cfg = self.compose_config(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 256, in _load_configuration
    cfg = self._merge_defaults_into_config(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 804, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, system_list)
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 777, in merge_defaults_list_into_config
    merged_cfg = self._merge_config(
  File "D:\Anaconda\envs\deepke\lib\site-packages\hydra\_internal\config_loader_impl.py", line 715, in _merge_config
    raise MissingConfigException(msg, new_cfg, options)
hydra.errors.MissingConfigException: Could not load hydra/output/custom.
Available options:
	default
修改了都没用啊

**Comment by xxupiano** [comment]
请检查hydra版本是否为1.0.6

**Comment by meimengiii** [comment]
没问题，是1.0.6
