### ISSUE TITLE
多显卡训练问题

### ISSUE THREAD

**Issue by n1ghtmar4** [zjunlp/deepke#44]
您好，我在使用多个显卡训练的时候开始出现报错，但之前使用单显卡的时候没有报错。
我只在main.py中添加了语句model = nn.DataParallel(model)，训练的模型是transformer。
报错信息如下：
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 93, in main
    train_loss = train(epoch, model, train_dataloader, optimizer, criterion, device, writer, cfg)
  File "/root/joi/deepke/trainer.py", line 21, in train
    y_pred = model(x)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/joi/deepke/models/Transformer.py", line 25, in forward
    last_layer_hidden_state, all_hidden_states, all_attentions = self.transformer(inputs, key_padding_mask=mask)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/joi/deepke/module/Transformer.py", line 134, in forward
    layer_outputs = layer_module(hidden_states, key_padding_mask, attention_mask, head_mask[i])
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/joi/deepke/module/Transformer.py", line 97, in forward
    attention_outputs = self.attention(hidden_states, key_padding_mask, attention_mask, head_mask)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/joi/deepke/module/Transformer.py", line 55, in forward
    attention_outputs = self.multihead_attention(x, x, x, key_padding_mask, attention_mask, head_mask)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/joi/deepke/module/Attention.py", line 114, in forward
    attention_out, attention_weight = self.attention(q, k, v, mask_out=mask_out, head_mask=head_mask)
  File "/root/anaconda3/envs/NER/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/joi/deepke/module/Attention.py", line 38, in forward
    attention_weight.masked_fill_(mask_out, -1e8)
RuntimeError: The expanded size of the tensor (270) must match the existing size (96) at non-singleton dimension 3.  Target sizes: [1, 4, 270, 270].  Tensor sizes: [1, 1, 1, 96]

**Comment by yuwl798180** [comment]
你好，多卡训练暂时没有实现。
transformer这块由于调用的 `transformers` 你可以具体查看下对于多gpu的使用。
