### ISSUE TITLE
我想用自己的数据训练模板，出现错误了

### ISSUE THREAD

**Issue by rockman1989** [zjunlp/deepke#45]
你好，你知道这个是什么错误吗？
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main()
  File "/root/miniconda3/envs/openNRE/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/root/miniconda3/envs/openNRE/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/root/miniconda3/envs/openNRE/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/root/miniconda3/envs/openNRE/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 46, in main
    preprocess(cfg)
  File "/root/deepke/deepke/preprocess.py", line 131, in preprocess
    _serialize_sentence(train_data, serial, cfg)
  File "/root/deepke/deepke/preprocess.py", line 55, in _serialize_sentence
    head_idx, tail_idx = d['tokens'].index('head'), d['tokens'].index('tail')
ValueError: 'tail' is not in list

**Comment by yuwl798180** [comment]
你好，错误的最后一行：ValueError: 'tail' is not in list

**Comment by UserJTZhang** [comment]
请问解决了吗，我也遇到这个问题是什么原因导致的呢

**Comment by rockman1989** [comment]
> 请问解决了吗，我也遇到这个问题是什么原因导致的呢

这个问题我认为是数据格式问题。后来由于时间有限，我没有继续使用这个框架了
