### ISSUE TITLE
re把数据集修改成自己的数据集后分类数增加，在哪里修改

### ISSUE THREAD

**Issue by liujunshanhelen** [zjunlp/DeepKE#453]
![Uploading image.png…]()

Traceback (most recent call last):
  File "run.py", line 180, in <module>
    main()
  File "/home/ljs/.local/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/ljs/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/ljs/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/ljs/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/ljs/.local/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/ljs/.local/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/ljs/.local/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "run.py", line 111, in main
    train_loss = train(epoch, model, train_dataloader, optimizer, criterion, device, writer, cfg)
  File "/home/ljs/miniconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/standard/tools/trainer.py", line 41, in train
    loss = criterion(y_pred, y)
  File "/home/ljs/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ljs/.local/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1163, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/home/ljs/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target 11 is out of bounds.

**Comment by BeasterYong** [comment]
您好，可以尝试修改`example/re/standard/conf/embedding.yaml`中的关系数目

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
