### ISSUE TITLE
运行报错RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Sangs3112** [zjunlp/DeepKE#460]
**Describe the question**
> A clear and concise description of what the question is.
你好，我在4090GPU下运行开箱即用的模块，运行predict.py会产生如下报错
Traceback (most recent call last):
  File "predict.py", line 57, in main
    result = model.predict(text)
  File "/home/sangs/project/DeepKE/example/triple/cnschema/InferBert.py", line 90, in predict
    logits = self.model(input_ids, segment_ids, input_mask,valid_ids)
  File "/home/sangs/.conda/envs/DeepKE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sangs/project/DeepKE/example/triple/cnschema/InferBert.py", line 16, in forward
    sequence_output = self.bert(input_ids, token_type_ids, attention_mask, head_mask=None)[0]
  File "/home/sangs/.conda/envs/DeepKE/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sangs/.conda/envs/DeepKE/lib/python3.8/site-packages/pytorch_transformers/modeling_bert.py", line 689, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype) # fp16 compatibility
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
请问如何解决，感谢！

**Comment by Sangs3112** [comment]
我的example中的每一个模型尝试运行的时候都有这个问题，好像是cuda版本的问题，但是我跑其他项目都可以

**Comment by zxlzr** [comment]
您好，建议您切换其他电脑，或者使用cpu跑下，如果能跑通可能是cuda版本问题

**Comment by xxupiano** [comment]
可能是pytorch安装版本和cuda不对应，建议根据pytorch官网指导安装

**Comment by Sangs3112** [comment]
如何只用CPU跑呢cnschema呢

**Comment by xxupiano** [comment]
https://github.com/zjunlp/DeepKE/blob/f35192387d8cf188b3583907d644ef2577f03fba/example/triple/cnschema/InferBert.py#L36 根据这一行代码，如果您正确安装了CPU的pytorch，是会自动在CPU上跑的

**Comment by zxlzr** [comment]
请问您的issue解决了吗
