### ISSUE TITLE
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

### ISSUE THREAD

**Issue by ljhssga** [zjunlp/DeepKE#467]
**Describe the bug**
> A clear and concise description of what the bug is.

使用官方给的脚本https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE.md，运行后报错
Traceback (most recent call last):
  File "/home/llen/DeepKE-main/example/llm/run.py", line 42, in <module>
    generation_output = model.generate(input_ids=input_ids, generation_config=GenerationConfig(max_length=1024, max_new_tokens=512, return_dict_in_generate=True))
  File "/root/miniconda3/envs/deepke-llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/deepke-llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1602, in generate
    return self.greedy_search(
  File "/root/miniconda3/envs/deepke-llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2489, in greedy_search
    raise ValueError("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.

虚拟环境与版本都是按照requirements.txt安装的

**Environment (please complete the following information):**
 - OS: [e.g. mac / window]
 - Python Version [e.g. 3.6]

transformers==4.33.0
torch==2.0.0

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.
[code.zip](https://github.com/zjunlp/DeepKE/files/14986465/code.zip)

**Comment by ljhssga** [comment]
将代码改为
generation_output = model.generate(input_ids=input_ids, generation_config=GenerationConfig(max_length=1024, max_new_tokens=512, return_dict_in_generate=True),**pad_token_id=tokenizer.eos_token_id**)

已解决

**Comment by zxlzr** [comment]
感谢您关注本项目和OneKE，请问您的问题解决了吗？
