### ISSUE TITLE
Traceback (most recent call last):   File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 928, in from_pretrained     raise EnvironmentError

### ISSUE THREAD

**Issue by huilema** [zjunlp/DeepKE#470]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 928, in from_pretrained
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict.py", line 103, in main
    model = LM(cfg)
  File "/root/DeepKE-main/example/triple/cnschema/LMModel.py", line 15, in __init__
    self.bert = BertModel.from_pretrained(cfg.lm_file, num_hidden_layers=cfg.num_hidden_layers)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 935, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load weights for 'hfl/chinese-bert-wwm'. Make sure that:

- 'hfl/chinese-bert-wwm' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'hfl/chinese-bert-wwm' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by zxlzr** [comment]
Hi, please make sure that you have the corrected pre-trained language model in the folder. Maybe the model is corrupted.

**Comment by zxlzr** [comment]
hi, have you solved your issue?
