### ISSUE TITLE
cmd 运行example/re/standard/run.py一直报错

### ISSUE THREAD

**Issue by yin-xxxxxx** [zjunlp/DeepKE#480]
C:\Users\Ylab\deepke\example\re\standard>python run.py
Traceback (most recent call last):
  File "C:\Users\Ylab\deepke\example\re\standard\run.py", line 2, in <module>
    import hydra
  File "D:\python\Lib\site-packages\hydra\__init__.py", line 5, in <module>
    from hydra import utils
  File "D:\python\Lib\site-packages\hydra\utils.py", line 10, in <module>
    from hydra._internal.utils import (
  File "D:\python\Lib\site-packages\hydra\_internal\utils.py", line 21, in <module>
    from hydra.core.utils import get_valid_filename, split_config_path
  File "D:\python\Lib\site-packages\hydra\core\utils.py", line 17, in <module>
    from hydra.core.hydra_config import HydraConfig
  File "D:\python\Lib\site-packages\hydra\core\hydra_config.py", line 6, in <module>
    from hydra.conf import HydraConf
  File "D:\python\Lib\site-packages\hydra\conf\__init__.py", line 62, in <module>
    class JobConf:
  File "D:\python\Lib\site-packages\hydra\conf\__init__.py", line 87, in JobConf
    @dataclass
  File "D:\python\Lib\dataclasses.py", line 1268, in dataclass
    return wrap(cls)
  File "D:\python\Lib\dataclasses.py", line 1258, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "D:\python\Lib\dataclasses.py", line 994, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))

  File "D:\python\Lib\dataclasses.py", line 852, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factor

**Comment by xxupiano** [comment]
请问hydra版本是否安装正确？ https://github.com/zjunlp/DeepKE/blob/main/requirements.txt#L2

**Comment by yin-xxxxxx** [comment]
> 请问hydra版本是否安装正确？ https://github.com/zjunlp/DeepKE/blob/main/requirements.txt#L2

对的，1.0.6

**Comment by yin-xxxxxx** [comment]
降低版本后解决了，又出现了新问题
C:\Users\Ylab\deepke\example\re\standard>python run.py
D:\python\Lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:572: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  (np.object, string),
Traceback (most recent call last):
  File "C:\Users\Ylab\deepke\example\re\standard\run.py", line 10, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\python\Lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\torch\utils\tensorboard\writer.py", line 15, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "D:\python\Lib\site-packages\tensorboard\summary\__init__.py", line 25, in <module>
    from tensorboard.summary import v1  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\tensorboard\summary\v1.py", line 26, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "D:\python\Lib\site-packages\tensorboard\plugins\histogram\summary.py", line 38, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "D:\python\Lib\site-packages\tensorboard\plugins\histogram\summary_v2.py", line 38, in <module>
    from tensorboard.util import tensor_util
  File "D:\python\Lib\site-packages\tensorboard\util\tensor_util.py", line 24, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "D:\python\Lib\site-packages\tensorboard\compat\tensorflow_stub\__init__.py", line 25, in <module>
    from .dtypes import as_dtype  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py", line 572, in <module>
    (np.object, string),
     ^^^^^^^^^
  File "D:\python\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?

**Comment by xxupiano** [comment]
numpy版本问题，请严格按照requirements中的版本号安装

**Comment by dcosmice** [comment]
> numpy版本问题，请严格按照requirements中的版本号安装

您好，按版本安装，并在pretrained后加入预训练模型后仍然出现如下问题：
[2024-04-24 16:50:05,927][deepke.relation_extraction.standard.tools.preprocess][INFO] - use bert tokenizer...
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<u
rllib3.connection.HTTPSConnection object at 0x000002BD5FC11670>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
[2024-04-24 16:50:26,036][huggingface_hub.utils._http][WARNING] - 'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-bas
e-chinese/resolve/main/vocab.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002BD5FC11670>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/bert-base-chinese/resolve/main/vocab.txt
Traceback (most recent call last):
  File "run.py", line 61, in main
    preprocess(cfg)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\relation_extraction\standard\tools\preprocess.py", line 208, in preprocess     
    _lm_serialize(train_data, cfg)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\relation_extraction\standard\tools\preprocess.py", line 120, in _lm_serialize  
    tokenizer = BertTokenizer.from_pretrained(cfg.lm_file)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\huggingface_hub\file_download.py", line 1148, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ylab/.cache\\huggingface\\hub\\models--bert-base-chinese\\refs\\main'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by dcosmice** [comment]
> 请问您还有其他问题吗？

有的，参考469后还是和469一样的错误
[2024-04-26 09:33:11,404][__main__][INFO] - device: cpu
[2024-04-26 09:33:11,404][deepke.relation_extraction.standard.tools.preprocess][INFO] - ===== start preprocess data =====
[2024-04-26 09:33:11,404][deepke.relation_extraction.standard.tools.preprocess][INFO] - load raw files...
[2024-04-26 09:33:11,404][utils.ioUtils][INFO] - load csv from C:\Users\Ylab\DeepKE\example\re\standard\data/origin\train.csv
[2024-04-26 09:33:11,410][utils.ioUtils][INFO] - load csv from C:\Users\Ylab\DeepKE\example\re\standard\data/origin\valid.csv
[2024-04-26 09:33:11,412][utils.ioUtils][INFO] - load csv from C:\Users\Ylab\DeepKE\example\re\standard\data/origin\test.csv
[2024-04-26 09:33:11,415][utils.ioUtils][INFO] - load csv from C:\Users\Ylab\DeepKE\example\re\standard\data/origin\relation.csv
[2024-04-26 09:33:11,415][deepke.relation_extraction.standard.tools.preprocess][INFO] - clean data...
[2024-04-26 09:33:11,415][deepke.relation_extraction.standard.tools.preprocess][INFO] - convert relation into index...
[2024-04-26 09:33:11,418][deepke.relation_extraction.standard.tools.preprocess][INFO] - verify whether use pretrained language models...
[2024-04-26 09:33:11,418][deepke.relation_extraction.standard.tools.preprocess][INFO] - use pretrained language models serialize sentence...
[2024-04-26 09:33:11,418][deepke.relation_extraction.standard.tools.preprocess][INFO] - use bert tokenizer...
Traceback (most recent call last):
  File "run.py", line 61, in main
    preprocess(cfg)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\relation_extraction\standard\tools\preprocess.py", line 208, in preprocess     
    _lm_serialize(train_data, cfg)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\deepke-2.2.7-py3.8.egg\deepke\relation_extraction\standard\tools\preprocess.py", line 120, in _lm_serialize  
    tokenizer = BertTokenizer.from_pretrained(cfg.lm_file)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Ylab\DeepKE\venv\lib\site-packages\huggingface_hub\file_download.py", line 1148, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Ylab/.cache\\huggingface\\hub\\models--bert-base-chinese\\refs\\main'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

请问怎么解决

**Comment by zxlzr** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Ylab/.cache\huggingface\hub\models--bert-base-chinese\refs\main'  请您检查路径下是否有下载好的模型，路径是否正确

**Comment by dcosmice** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Ylab/.cache\huggingface\hub\models--bert-base-chinese\refs\main' 请您检查路径下是否有下载好的模型，路径是否正确

在MIAN中添加了模型，也在huggingface下载了TEXT,出现如下问题了捏：

requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

**Comment by zxlzr** [comment]
应该是这个文件vocab.txt  缺失

**Comment by dcosmice** [comment]
> 应该是这个文件vocab.txt 缺失

再次运行错误又变成无法访问了，这是咋回事呀
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Ylab/.cache\\huggingface\\hub\\models--bert-base-chinese\\refs\\main'

**Comment by zxlzr** [comment]
您可以检查下路径的权限设置，以及这路径是否存在。

**Comment by dcosmice** [comment]
> 应该是这个文件vocab.txt 缺失

这个文件还应该在哪个路径下添加呢？
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-chinese/resolve/main/vocab.txt (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:1131)')))

**Comment by zxlzr** [comment]
和bert模型权重同一个目录下

**Comment by dcosmice** [comment]
> 和bert模型权重同一个目录下

是指和config.json、pytorch_model.bin文件在同一目录下吗，如果是的话，我已经放了

**Comment by xxupiano** [comment]
C:\Users\Ylab/.cache\huggingface\hub\models--bert-base-chinese\refs\main 路径斜杠错误，请使用linux跑实验。如果win，请尝试使用双斜杠

**Comment by dcosmice** [comment]
> C:\Users\Ylab/.cache\huggingface\hub\models--bert-base-chinese\refs\main 路径斜杠错误，请使用linux跑实验。如果win，请尝试使用双斜杠\\

好的，能跑了，非常非感谢两位大大！！

另外小白请教几个问题：
1、我运行下来发现好像只能实现RE，如果还想实现NER、AE等怎么实现，运行哪些对应的文件？
如下：
是否使用范例[y/n]，退出请输入: exit .... n
请输入句子：碳具有多孔的特点
请输入句中需要预测关系的头实体：碳
请输入头实体类型：1
请输入句中需要预测关系的尾实体：多孔
请输入尾实体类型：2

2、目前好像使用model中的lm.yaml，这个是预训练时只用了LSTM模型吗，但是好像又看到BERT、BiLSTM模型？？（即预训练时用了哪些模型？）
[2024-04-26 14:38:39,775][__main__][INFO] - model name: lm
[2024-04-26 14:38:39,775][__main__][INFO] -
 LM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (bilstm): RNN(
    (rnn): LSTM(768, 50, batch_first=True, dropout=0.3, bidirectional=True)
  )
  (fc): Linear(in_features=100, out_features=11, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)

**Comment by xxupiano** [comment]
1. example下有各种任务的代码
2. 是指用了BERT，那是因为BERT模型里的BertPooler包含BiLSTM
请仔细阅读README后再使用DeepKE

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
