### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by Bibaba-King** [zjunlp/DeepKE#490]
[2024-05-03 21:46:06,808][__main__][INFO] - ========== Start training ==========
Traceback (most recent call last):
  File "run.py", line 111, in main
    train_loss = train(epoch, model, train_dataloader, optimizer, criterion, device, writer, cfg)
  File "/home/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/standard/tools/trainer.py", line 36, in train
    y_pred = model(x)
  File "/home/anaconda3/envs/deepke/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/relation_extraction/standard/models/PCNN.py", line 39, in forward
    mask = seq_len_to_mask(lens)
  File "/home/anaconda3/envs/deepke/lib/python3.8/site-packages/deepke/attribution_extraction/standard/utils/nnUtils.py", line 54, in seq_len_to_mask
    mask = broad_cast_seq_len.ge(seq_len.unsqueeze(1))
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

实验环境：
NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2 
NVIDIA GeForce RTX 4090

想知道这是什么类型的错误？应该如何解决？期待回复，感谢！

**Comment by xxupiano** [comment]
请检查torch和cuda版本是否对应，GPU使用会否异常

**Comment by Bibaba-King** [comment]
十分感谢 问题已解决
