### ISSUE TITLE
llm范例run.py执行问题

### ISSUE THREAD

**Issue by zhuweigang** [zjunlp/DeepKE#542]
llm范例按照README.md安装了：
pip install git+https://github.com/zjunlp/EasyInstruct
pip install hydra-core

然后执行run.py报如下错误：

OS: ubuntu 20.04
Python Version 3.9
NVIDIA RTX 3090

Screenshots:
Traceback (most recent call last):
  File "/root/DeepKE/example/llm/LLMICL/run.py", line 6, in <module>
    from easyinstruct.prompts import IEPrompt
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/easyinstruct/__init__.py", line 1, in <module>
    from .prompts import *
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/easyinstruct/prompts/__init__.py", line 1, in <module>
    from .base_prompt import BasePrompt
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/easyinstruct/prompts/base_prompt.py", line 3, in <module>
    import cohere
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/cohere/__init__.py", line 3, in <module>
    from .types import (
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/cohere/types/__init__.py", line 22, in <module>
    from .chat_stream_end_event import ChatStreamEndEvent
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/cohere/types/chat_stream_end_event.py", line 10, in <module>
    from .non_streamed_chat_response import NonStreamedChatResponse
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/cohere/types/non_streamed_chat_response.py", line 15, in <module>
    from .message import Message
  File "/root/anaconda3/envs/deepke/lib/python3.9/site-packages/cohere/types/message.py", line 17, in <module>
    class Message_Chatbot(UncheckedBaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/root/anaconda3/envs/deepke/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

麻烦大神帮看一下是什么原因哈

**Comment by OE-Heart** [comment]
可能是 `cohere` 和 `pydantic` 的版本之间存在不兼容问题，请您尝试安装cohere==4.31.0，或者按原步骤重新安装我们更新了安装依赖的easyinstruct

**Comment by zhuweigang** [comment]
指定安装corehere==4.31.0后，报另一个错。。

**Comment by OE-Heart** [comment]
还是因为版本冲突的问题，您试一试重新pip install git+https://github.com/zjunlp/EasyInstruct吧

**Comment by zhuweigang** [comment]
重装EasyInstruct后问题解决，谢谢
