### ISSUE TITLE
使用deepke-llm微调zhixi报错

### ISSUE THREAD

**Issue by Da1zheng** [zjunlp/DeepKE#549]
**Describe the bug**
> A clear and concise description of what the bug is.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 855472) of binary: /share/home/HCI/daizheng/anaconda3/envs/deepke/bin/python
Traceback (most recent call last):
  File "/share/home/HCI/daizheng/anaconda3/envs/deepke/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/share/home/HCI/daizheng/anaconda3/envs/deepke/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/share/home/HCI/daizheng/anaconda3/envs/deepke/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/share/home/HCI/daizheng/anaconda3/envs/deepke/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/share/home/HCI/daizheng/anaconda3/envs/deepke/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/share/home/HCI/daizheng/anaconda3/envs/deepke/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-11_15:54:30
  host      : gpu03
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 855472)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Environment (please complete the following information):**
 - OS: ubuntu22.04
 - Python Version=3.9

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://github.com/zjunlp/DeepKE/assets/76696911/47586da8-57ce-4b29-aa71-b071a1a8db7c)

**Additional context**
> Add any other context about the problem here.

**Comment by Da1zheng** [comment]
![image](https://github.com/zjunlp/DeepKE/assets/76696911/624ac294-5d35-4bf2-a41e-ff2b587ee87f)
除了以上的报错信息之外，还有这个问题，请问怎么解决呢？谢谢！

**Comment by guihonghao** [comment]
查看命令行中的显卡配置，命令是否正确

**Comment by Da1zheng** [comment]
> 查看命令行中的显卡配置，命令是否正确

谢谢，已经解决。修改了/src/model/loader.py line53，加载Tokenizer时增加了一个参数unk_token="<unk>"，之后可以成功运行。
