### ISSUE TITLE
Linux 运行re run.py huggingface_hu 问题

### ISSUE THREAD

**Issue by yihanxiaoxiao** [zjunlp/DeepKE#584]
2024年6月份，没有代理和梯子huggingface_hu 无法访问。查找资料后
安装huggingface_hub：6月份版本是Version: 0.23.4
1.pip install -U huggingface_hub
2.export HF_ENDPOINT=https://hf-mirror.com
3.huggingface-cli download --resume-download gpt2 --local-dir gpt2	
4.huggingface-cli download --repo-type dataset --resume-download wikitext --local-dir wikitext
可以成功运行 run.py并预测
2024年9月12号源码方式安装deepke，执行上述1234步骤，出现如下报错：
use bert tokenizer...
Traceback (most recent call last):
  File "run.py", line 61, in main
    preprocess(cfg)
  File "/test/local/anaconda3/envs/deepketest/lib/python3.8/site-packages/deepke-2.2.7-py3.8.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 208, in preprocess
    _lm_serialize(train_data, cfg)
  File "/test/local/anaconda3/envs/deepketest/lib/python3.8/site-packages/deepke-2.2.7-py3.8.egg/deepke/relation_extraction/standard/tools/preprocess.py", line 120, in _lm_serialize
    tokenizer = BertTokenizer.from_pretrained(cfg.lm_file)
  File "/test/local/anaconda3/envs/deepketest/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1763, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/test/local/anaconda3/envs/deepketest/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/test/local/anaconda3/envs/deepketest/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/test/local/anaconda3/envs/deepketest/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/disk/disk_20T/luoyujie/Model/bert-base-chinese'. Use `repo_type` argument if needed.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

后面发现huggingface_hub 版本是0.24,重新安装0.23.4
pip install huggingface_hub==0.23.4
再次执行234步骤后，运行run.py 还是报上述错误。
如何解决这个错误

**Comment by yihanxiaoxiao** [comment]
补充一下，使用Deepke Tag 中的2.2.7 没有上述问题，请确认并解决一下上面master 代码安装出现的错误。谢谢！

**Comment by BeasterYong** [comment]
您好，非常感谢您的提问，请您拉取最新的版本的代码并重试，感谢！

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
