### ISSUE TITLE
ModuleNotFoundError: No module named 'losses'

### ISSUE THREAD

**Issue by renmjie** [zjunlp/DeepKE#85]
**Describe the question**
> A clear and concise description of what the question is.

$ python run.py 
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    import deepke.relation_extraction.standard.models as models
  File "/home/rj/FG/lib/python3.6/site-packages/deepke/__init__.py", line 2, in <module>
    from .relation_extraction import *
  File "/home/rj/FG/lib/python3.6/site-packages/deepke/relation_extraction/__init__.py", line 2, in <module>
    from .document import *
  File "/home/rj/FG/lib/python3.6/site-packages/deepke/relation_extraction/document/__init__.py", line 1, in <module>
    from .model import *
  File "/home/rj/FG/lib/python3.6/site-packages/deepke/relation_extraction/document/model.py", line 4, in <module>
    from losses import ATLoss
ModuleNotFoundError: No module named 'losses'

**Comment by tlk1997** [comment]
找到该路径文件 losses前加个.
