### ISSUE TITLE
_serialize_sentence() missing 1 required positional argument: 'cfg'

### ISSUE THREAD

**Issue by wandugu** [zjunlp/DeepKE#88]
when running predict.py

是否使用范例[y/n]，退出请输入: exit .... y
Traceback (most recent call last):
  File "predict.py", line 154, in <module>
    main()
  File "/home/hmp/anaconda3/envs/python38/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/hmp/anaconda3/envs/python38/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/hmp/anaconda3/envs/python38/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/hmp/anaconda3/envs/python38/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/hmp/anaconda3/envs/python38/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/hmp/anaconda3/envs/python38/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/hmp/anaconda3/envs/python38/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "predict.py", line 89, in main
    data, rels = _preprocess_data(data, cfg)
  File "predict.py", line 29, in _preprocess_data
    _serialize_sentence(data, serial)
TypeError: _serialize_sentence() missing 1 required positional argument: 'cfg'

**Comment by tlk1997** [comment]
Thanks for using deepke. You can git pull the latest version to solve this issue.

**Comment by wandugu** [comment]
> Thanks for using deepke. You can git pull the latest code to solve this issue.

您好，我已经更新了最新代码，这个问题还是存在
